using System.Text;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Readers;

namespace ZeroAlloc.Rest.Tools;

public static class OpenApiInterfaceGenerator
{
    public static string Generate(string yamlOrJson, string @namespace, string interfaceName)
    {
        var reader = new OpenApiStringReader();
        var document = reader.Read(yamlOrJson, out var diagnostic);

        if (document == null)
            throw new InvalidOperationException("Failed to parse OpenAPI document.");
        if (diagnostic.Errors.Count > 0)
        {
            var errors = string.Join("; ", diagnostic.Errors.Select(e => e.Message));
            throw new InvalidOperationException($"OpenAPI parse errors: {errors}");
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Rest.Attributes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine("[ZeroAllocRestClient]");
        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");

        if (document.Paths != null)
        {
            foreach (var (path, pathItem) in document.Paths)
                foreach (var (operationType, operation) in pathItem.Operations)
                    EmitMethod(sb, path, operationType, operation);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateFromFile(string filePath, string @namespace, string interfaceName)
    {
        var content = File.ReadAllText(filePath);
        return Generate(content, @namespace, interfaceName);
    }

    public static async Task<string> GenerateFromFileAsync(
        string filePath, string @namespace, string interfaceName,
        CancellationToken ct = default)
    {
        var content = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName);
    }

    public static async Task<string> GenerateFromUrlAsync(
        string url, string @namespace, string interfaceName,
        CancellationToken ct = default)
    {
        using var http = new HttpClient();
        var content = await http.GetStringAsync(url, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName);
    }

    private static void EmitMethod(StringBuilder sb, string path,
        OperationType operationType, OpenApiOperation operation)
    {
        var httpAttr = operationType switch
        {
            OperationType.Get    => "Get",
            OperationType.Post   => "Post",
            OperationType.Put    => "Put",
            OperationType.Patch  => "Patch",
            OperationType.Delete => "Delete",
            _ => null
        };
        if (httpAttr is null) return;

        sb.AppendLine($"    [{httpAttr}(\"{path}\")]");

        var methodName = ToPascalCase(operation.OperationId
            ?? $"{httpAttr}{path.Replace("/", "_").Replace("{", "").Replace("}", "")}") + "Async";

        var parameters = new List<string>();

        if (operation.Parameters != null)
        {
            foreach (var param in operation.Parameters)
            {
                var typeName = MapSchemaType(param.Schema);
                var paramName = ToCamelCase(param.Name);
                var paramStr = param.In switch
                {
                    ParameterLocation.Query  => $"[Query] {typeName} {paramName}",
                    ParameterLocation.Header => $"[Header(\"{param.Name}\")] string {paramName}",
                    _ => $"{typeName} {paramName}"
                };
                parameters.Add(paramStr);
            }
        }

        if (operation.RequestBody != null)
            parameters.Add("[Body] object body");

        parameters.Add("CancellationToken ct = default");

        var returnType = GetReturnType(operation);
        sb.AppendLine($"    {returnType} {methodName}({string.Join(", ", parameters)});");
        sb.AppendLine();
    }

    private static string GetReturnType(OpenApiOperation operation)
    {
        foreach (var (statusCode, response) in operation.Responses)
        {
            if (!statusCode.StartsWith("2", StringComparison.Ordinal)) continue;
            if (response.Content == null || response.Content.Count == 0) return "Task";
            foreach (var (_, content) in response.Content)
            {
                if (content.Schema == null) continue;
                return $"Task<{MapSchemaTypeForReturn(content.Schema)}>";
            }
        }
        return "Task";
    }

    private static string MapSchemaTypeForReturn(OpenApiSchema schema)
    {
        if (schema.Type == "array" && schema.Items != null)
            return $"List<{MapSchemaTypeForReturn(schema.Items)}>";
        if (schema.Reference != null)
            return ToPascalCase(schema.Reference.Id);
        return schema.Type switch
        {
            "integer" => "int",
            "number"  => "double",
            "boolean" => "bool",
            "string"  => "string",
            _         => "object"
        };
    }

    private static string MapSchemaType(OpenApiSchema? schema) => schema?.Type switch
    {
        "integer" => "int",
        "number"  => "double",
        "boolean" => "bool",
        _ => "string"
    };

    /// <summary>Converts snake_case, kebab-case, or plain strings to PascalCase.</summary>
    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        var parts = s.Split('_', '-');
        var result = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0) continue;
            result.Append(char.ToUpper(part[0]));
            result.Append(part.Substring(1));
        }
        return result.Length > 0 ? result.ToString() : s;
    }

    private static string ToCamelCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        return char.ToLower(s[0]) + s.Substring(1);
    }
}
