using System.Text;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Readers;

namespace ZeroAlloc.Rest.Tools;

public static class OpenApiInterfaceGenerator
{
    public static string Generate(string yamlOrJson, string @namespace, string interfaceName)
    {
        var reader = new OpenApiStringReader();
        var document = reader.Read(yamlOrJson, out _);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Rest.Attributes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine("[ZeroAllocRestClient]");
        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");

        if (document?.Paths != null)
        {
            foreach (var (path, pathItem) in document.Paths)
            {
                foreach (var (operationType, operation) in pathItem.Operations)
                {
                    EmitMethod(sb, path, operationType, operation);
                }
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateFromFile(string filePath, string @namespace, string interfaceName)
    {
        var content = File.ReadAllText(filePath);
        return Generate(content, @namespace, interfaceName);
    }

    public static async Task<string> GenerateFromFileAsync(
        string filePath, string @namespace, string interfaceName,
        CancellationToken ct = default)
    {
        var content = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName);
    }

    public static async Task<string> GenerateFromUrlAsync(
        string url, string @namespace, string interfaceName,
        CancellationToken ct = default)
    {
        using var http = new HttpClient();
        var content = await http.GetStringAsync(url, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName);
    }

    private static void EmitMethod(StringBuilder sb, string path,
        OperationType operationType, OpenApiOperation operation)
    {
        var httpAttr = operationType switch
        {
            OperationType.Get    => "Get",
            OperationType.Post   => "Post",
            OperationType.Put    => "Put",
            OperationType.Patch  => "Patch",
            OperationType.Delete => "Delete",
            _ => null
        };
        if (httpAttr is null) return;

        sb.AppendLine($"    [{httpAttr}(\"{path}\")]");

        var methodName = ToPascalCase(operation.OperationId
            ?? $"{httpAttr}{path.Replace("/", "_").Replace("{", "").Replace("}", "")}") + "Async";

        var parameters = new List<string>();

        // Path and query parameters
        if (operation.Parameters != null)
        {
            foreach (var param in operation.Parameters)
            {
                var typeName = MapSchemaType(param.Schema);
                var paramName = ToCamelCase(param.Name);

                var paramStr = param.In switch
                {
                    ParameterLocation.Query  => $"[Query] {typeName} {paramName}",
                    ParameterLocation.Header => $"[Header(\"{param.Name}\")] string {paramName}",
                    _ => $"{typeName} {paramName}" // path param — no attribute
                };

                parameters.Add(paramStr);
            }
        }

        // Request body
        if (operation.RequestBody != null)
            parameters.Add("[Body] object body");

        parameters.Add("CancellationToken ct = default");

        sb.AppendLine($"    Task<object> {methodName}({string.Join(", ", parameters)});");
        sb.AppendLine();
    }

    private static string MapSchemaType(OpenApiSchema? schema) => schema?.Type switch
    {
        "integer" => "int",
        "number"  => "double",
        "boolean" => "bool",
        _ => "string"
    };

    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        return char.ToUpper(s[0]) + s.Substring(1);
    }

    private static string ToCamelCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        return char.ToLower(s[0]) + s.Substring(1);
    }
}
