<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>zeroalloc</ToolCommandName>
  </PropertyGroup>
  <Import Project="../ZeroAlloc.Rest.Tools.Shared/ZeroAlloc.Rest.Tools.Shared.projitems" Label="Shared" />
  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi.Readers" />
    <PackageReference Include="System.CommandLine" />
    <ProjectReference Include="../ZeroAlloc.Rest/ZeroAlloc.Rest.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ZeroAlloc.Rest.Tools.Tests" />
  </ItemGroup>
</Project>
