using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using ZeroAlloc.Rest.Generator.Models;

namespace ZeroAlloc.Rest.Generator;

internal static class ClientEmitter
{
    private static readonly DiagnosticDescriptor s_conflictingBodyDescriptor = new DiagnosticDescriptor(
        id: "ZRA001",
        title: "Conflicting body attributes",
        messageFormat: "Method '{0}' has both [Body] and [FormBody] parameters; only one is allowed",
        category: "ZeroAlloc.Rest.Generator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    internal static void Emit(SourceProductionContext ctx, ClientModel model)
    {
        // Collect unique method-level serializer types (ordered, deduped)
        var overrideSerializers = model.GetOverrideSerializerTypes();

        // Build a collision-free FQN → field name map
        var serializerFieldMap = new Dictionary<string, string>();
        var usedFieldNames = new List<string>();
        foreach (var st in overrideSerializers)
        {
            var fieldName = GetSerializerFieldName(st, usedFieldNames);
            usedFieldNames.Add(fieldName);
            serializerFieldMap[st] = fieldName;
        }

        var hasQueryParams = false;
        foreach (var m in model.Methods)
            foreach (var p in m.Parameters)
                if (p.Kind == ParameterKind.Query) { hasQueryParams = true; break; }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        if (hasQueryParams)
            sb.AppendLine("using ZeroAlloc.Collections;");
        sb.AppendLine("using ZeroAlloc.Rest;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{model.Accessibility} sealed partial class {model.ClassName} : {model.InterfaceName}, global::ZeroAlloc.Rest.IGeneratedRestClient<{model.ClassName}>");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly global::System.Diagnostics.ActivitySource _activitySource = new(\"ZeroAlloc.Rest\");");
        sb.AppendLine("    private static readonly global::System.Diagnostics.Metrics.Meter _meter = new(\"ZeroAlloc.Rest\");");
        sb.AppendLine("    private static readonly global::System.Diagnostics.Metrics.Counter<long> _requestsTotal = _meter.CreateCounter<long>(\"rest.requests_total\");");
        sb.AppendLine("    private static readonly global::System.Diagnostics.Metrics.Histogram<double> _requestDurationMs = _meter.CreateHistogram<double>(\"rest.request_duration_ms\");");
        sb.AppendLine("    private readonly System.Net.Http.HttpClient _httpClient;");
        sb.AppendLine("    private readonly ZeroAlloc.Rest.IRestSerializer _serializer;");
        // Override serializers are held and taken as IRestSerializer, like the main one, so an
        // internal serializer type never appears in the public constructor. Create resolves the
        // concrete types.
        foreach (var st in overrideSerializers)
            sb.AppendLine($"    private readonly ZeroAlloc.Rest.IRestSerializer {serializerFieldMap[st]};");
        sb.AppendLine();

        // Build constructor parameter list
        var ctorParams = new System.Collections.Generic.List<string>
        {
            "System.Net.Http.HttpClient httpClient",
            // Always IRestSerializer, even with an interface-level [Serializer]: that type may be
            // internal while the client is public. Create resolves the concrete type.
            "ZeroAlloc.Rest.IRestSerializer serializer"
        };
        foreach (var st in overrideSerializers)
        {
            var fieldName = serializerFieldMap[st];
            ctorParams.Add($"ZeroAlloc.Rest.IRestSerializer {fieldName.Substring(1)}"); // strip leading '_' for param name
        }

        sb.AppendLine($"    public {model.ClassName}({string.Join(", ", ctorParams)})");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("        _serializer = serializer;");
        foreach (var st in overrideSerializers)
        {
            var fieldName = serializerFieldMap[st];
            sb.AppendLine($"        {fieldName} = {fieldName.Substring(1)};");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        EmitGeneratedClientMembers(sb, model, overrideSerializers);

        foreach (var method in model.Methods)
            EmitMethod(ctx, sb, model.InterfaceName, method, serializerFieldMap);

        EmitRecordFailure(sb);

        var anyReturnsResult = false;
        foreach (var m in model.Methods)
            if (m.ReturnsResult) { anyReturnsResult = true; break; }
        if (anyReturnsResult)
            EmitCreateHttpError(sb);

        if (hasQueryParams)
        {
            sb.AppendLine("    private static void AppendToUrl(ZeroAlloc.Collections.HeapPooledList<char> list, System.ReadOnlySpan<char> value)");
            sb.AppendLine("    {");
            sb.AppendLine("        for (var i = 0; i < value.Length; i++) list.Add(value[i]);");
            sb.AppendLine("    }");
            sb.AppendLine("    private static void AppendToUrl(ZeroAlloc.Collections.HeapPooledList<char> list, char value)");
            sb.AppendLine("        => list.Add(value);");
        }

        sb.AppendLine("}");

        ctx.AddSource($"{model.InterfaceName}.g.cs", sb.ToString());
    }

    // IGeneratedRestClient<TSelf>: how Add{I} and the Resilience bridge build the client and register
    // its serializers, with no reflection or ActivatorUtilities. Implemented explicitly, so the client
    // gains no public Create or AddSerializers that could clash with the interface's own methods.
    private static void EmitGeneratedClientMembers(StringBuilder sb, ClientModel model, IReadOnlyList<string> overrideSerializers)
    {
        var self = $"global::ZeroAlloc.Rest.IGeneratedRestClient<{model.ClassName}>";
        const string GetRequired = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";
        const string TryAddSingleton = "global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton";

        var serializerArg = model.SerializerTypeName != null
            ? $"{GetRequired}<{model.SerializerTypeName}>(services)"
            : $"global::ZeroAlloc.Rest.RestSerializerServiceProviderExtensions.GetRequiredRestSerializer<{model.InterfaceName}>(services)";
        var ctorArgs = new List<string> { "httpClient", serializerArg };
        foreach (var st in overrideSerializers)
            ctorArgs.Add($"{GetRequired}<{st}>(services)");

        sb.AppendLine($"    static {model.ClassName} {self}.Create(global::System.Net.Http.HttpClient httpClient, global::System.IServiceProvider services)");
        sb.AppendLine($"        => new {model.ClassName}(");
        for (var i = 0; i < ctorArgs.Count; i++)
            sb.AppendLine($"            {ctorArgs[i]}{(i < ctorArgs.Count - 1 ? "," : ");")}");
        sb.AppendLine();

        sb.AppendLine($"    static void {self}.AddSerializers(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::ZeroAlloc.Rest.ZeroAllocClientOptions options)");
        sb.AppendLine("    {");
        if (model.SerializerTypeName != null)
        {
            // The interface-level [Serializer] fixes this client's serializer at compile time, so a
            // UseSerializer for it is a contradiction: reject it instead of ignoring it.
            var interfaceFullName = string.IsNullOrEmpty(model.Namespace)
                ? model.InterfaceName
                : model.Namespace + "." + model.InterfaceName;
            var serializerDisplayName = StripGlobal(model.SerializerTypeName);
            sb.AppendLine("        if (options.SerializerType is not null || options.SerializerInstance is not null)");
            sb.AppendLine("            throw new global::System.InvalidOperationException(");
            sb.AppendLine($"                \"The REST client '{interfaceFullName}' declares [Serializer(typeof({serializerDisplayName}))], \" +");
            sb.AppendLine("                \"so it cannot also be given a serializer with UseSerializer. Use one or the other.\");");
            sb.AppendLine($"        {TryAddSingleton}<{model.SerializerTypeName}>(services);");
        }
        else
        {
            // UseSerializer is per client: keyed by the interface, it never touches the app-wide
            // IRestSerializer, so two clients cannot overwrite each other's serializer.
            sb.AppendLine($"        global::ZeroAlloc.Rest.GeneratedRestClient.AddPerClientSerializer<{model.InterfaceName}>(services, options);");
        }
        foreach (var st in overrideSerializers)
            sb.AppendLine($"        {TryAddSingleton}<{st}>(services);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitMethod(SourceProductionContext ctx, StringBuilder sb, string interfaceName, MethodModel method, IReadOnlyDictionary<string, string> serializerFieldMap)
    {
        var ctParam = FindCancellationToken(method.Parameters);
        var ctArg = ctParam != null ? ctParam.Name : "default";
        var pathParams = FilterParameters(method.Parameters, ParameterKind.Path);
        var queryParams = FilterParameters(method.Parameters, ParameterKind.Query);
        var bodyParam = FirstOrDefault(method.Parameters, ParameterKind.Body);
        var formBodyParam = FirstOrDefault(method.Parameters, ParameterKind.FormBody);
        var headerParams = FilterParameters(method.Parameters, ParameterKind.Header);

        if (bodyParam != null && formBodyParam != null)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(s_conflictingBodyDescriptor, Location.None, method.Name));
            // Still emit valid (if incomplete) code so compilation continues
            formBodyParam = null; // suppress the FormBody branch
        }

        // If the method has its own [Serializer], use that injected field; otherwise fall back to _serializer.
        var serializerExpr = method.SerializerTypeName != null && serializerFieldMap.TryGetValue(method.SerializerTypeName, out var fieldName)
            ? fieldName
            : "_serializer";

        // IL3051/IL2046: Previously we emitted [RequiresDynamicCode] / [RequiresUnreferencedCode]
        // here, but the user-authored interface doesn't carry those annotations — ILC rejects
        // the mismatch and forces consumers to propagate the Requires attributes to every
        // caller. Switch to [UnconditionalSuppressMessage] which flows no obligation to the
        // caller: the serializer is provided by the consumer, so its trim/AOT-unsafety is
        // their concern, not the client wrapper's.
        sb.AppendLine("    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"IRestSerializer is provided by the consumer; its trim-unsafety is their concern. The generated client only forwards the call.\")]");
        sb.AppendLine("    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"IRestSerializer is provided by the consumer; its AOT-unsafety is their concern. The generated client only forwards the call.\")]");
        sb.AppendLine($"    public async {method.ReturnTypeName} {method.Name}({BuildParamList(method.Parameters)})");
        sb.AppendLine("    {");

        var spanName = $"{interfaceName}.{method.Name}";
        sb.AppendLine($"        using var __activity = _activitySource.StartActivity(\"{spanName}\");");
        sb.AppendLine($"        const string __RestMethodTag = \"{spanName}\";");
        sb.AppendLine($"        const string __httpMethod = \"{method.HttpMethod.ToUpper()}\";");
        sb.AppendLine($"        __activity?.SetTag(\"http.method\", __httpMethod);");
        sb.AppendLine($"        __activity?.SetTag(\"rest.method\", __RestMethodTag);");
        sb.AppendLine($"        var __sw = global::System.Diagnostics.Stopwatch.GetTimestamp();");

        EmitUrlBuilding(sb, method.Route, pathParams, queryParams);
        EmitRequestCreation(sb, method, headerParams, bodyParam, formBodyParam, ctArg, serializerExpr);
        EmitSendAndResponse(sb, method, ctParam?.Name, serializerExpr);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitUrlBuilding(StringBuilder sb, string route,
        List<ParameterModel> pathParams, List<ParameterModel> queryParams)
    {
        if (pathParams.Count == 0 && queryParams.Count == 0)
        {
            sb.AppendLine($"        var url = \"{route}\";");
            return;
        }

        // Build the route with path interpolation
        var routeExpr = route;
        foreach (var p in pathParams)
            routeExpr = routeExpr.Replace("{" + p.Name + "}", $"{{Uri.EscapeDataString({p.Name}.ToString())}}");

        if (queryParams.Count == 0)
        {
            sb.AppendLine($"        var url = $\"{routeExpr}\";");
        }
        else
        {
            sb.AppendLine($"        var urlBase = $\"{routeExpr}\";");
            sb.AppendLine("        using var urlBuilder = new ZeroAlloc.Collections.HeapPooledList<char>(urlBase.Length + 64);");
            sb.AppendLine("        AppendToUrl(urlBuilder, urlBase.AsSpan());");
            sb.AppendLine("        var hasQuery = false;");
            foreach (var q in queryParams)
            {
                if (q.IsCollection)
                {
                    sb.AppendLine($"        if ({q.Name} != null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            foreach (var __item in {q.Name})");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                if (__item == null) continue;");
                    sb.AppendLine($"                AppendToUrl(urlBuilder, hasQuery ? '&' : '?');");
                    sb.AppendLine($"                AppendToUrl(urlBuilder, \"{q.QueryName}=\".AsSpan());");
                    sb.AppendLine($"                AppendToUrl(urlBuilder, System.Uri.EscapeDataString(__item.ToString()!).AsSpan());");
                    sb.AppendLine("                hasQuery = true;");
                    sb.AppendLine("            }");
                    sb.AppendLine("        }");
                }
                else if (q.IsNullable)
                {
                    sb.AppendLine($"        if ({q.Name} != null)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            AppendToUrl(urlBuilder, hasQuery ? '&' : '?');");
                    sb.AppendLine($"            AppendToUrl(urlBuilder, \"{q.QueryName}=\".AsSpan());");
                    sb.AppendLine($"            AppendToUrl(urlBuilder, System.Uri.EscapeDataString({q.Name}!.ToString()!).AsSpan());");
                    sb.AppendLine("            hasQuery = true;");
                    sb.AppendLine("        }");
                }
                else
                {
                    sb.AppendLine($"        AppendToUrl(urlBuilder, hasQuery ? '&' : '?');");
                    sb.AppendLine($"        AppendToUrl(urlBuilder, \"{q.QueryName}=\".AsSpan());");
                    sb.AppendLine($"        AppendToUrl(urlBuilder, System.Uri.EscapeDataString({q.Name}.ToString()!).AsSpan());");
                    sb.AppendLine("        hasQuery = true;");
                }
            }
            sb.AppendLine("        var url = new string(urlBuilder.AsReadOnlySpan());");
        }
    }

    private static void EmitRequestCreation(StringBuilder sb, MethodModel method,
        List<ParameterModel> headerParams, ParameterModel? bodyParam, ParameterModel? formBodyParam,
        string ctArg, string serializerExpr)
    {
        sb.AppendLine($"        using var request = new System.Net.Http.HttpRequestMessage(");
        sb.AppendLine($"            System.Net.Http.HttpMethod.{Capitalize(method.HttpMethod)},");
        sb.AppendLine($"            url);");
        sb.AppendLine($"        request.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue({serializerExpr}.ContentType));");

        // Static headers declared with [Header("Name", Value = "...")] are added additively.
        // For Accept, this means both the serializer's content type and the static value will
        // appear in the header. This is intentional — use ConfigureHttpClient to override
        // the serializer's Accept if exclusive control is needed.
        foreach (var (name, value) in method.StaticHeaders)
            sb.AppendLine($"        request.Headers.TryAddWithoutValidation(\"{name}\", \"{value}\");");

        foreach (var h in headerParams)
            sb.AppendLine($"        request.Headers.TryAddWithoutValidation(\"{h.HeaderName}\", {h.Name}?.ToString());");

        if (bodyParam != null)
        {
            sb.AppendLine("        var bodyStream = new System.IO.MemoryStream();");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            await {serializerExpr}.SerializeAsync(bodyStream, {bodyParam.Name}, {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch");
            sb.AppendLine("        {");
            sb.AppendLine("            bodyStream.Dispose();");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");
            sb.AppendLine("        bodyStream.Position = 0;");
            sb.AppendLine("        request.Content = new System.Net.Http.StreamContent(bodyStream);");
            sb.AppendLine($"        request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue({serializerExpr}.ContentType);");
        }

        if (formBodyParam != null)
        {
            sb.AppendLine($"        request.Content = new System.Net.Http.FormUrlEncodedContent({formBodyParam.Name});");
        }
    }

    // callerToken is the name of the method's CancellationToken parameter, or null when it has none.
    private static void EmitSendAndResponse(StringBuilder sb, MethodModel method, string? callerToken, string serializerExpr)
    {
        var ctArg = callerToken ?? "default";
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            using var response = await _httpClient.SendAsync(request, {ctArg}).ConfigureAwait(false);");
        sb.AppendLine("            var __statusCode = (int)response.StatusCode;");
        sb.AppendLine("            var __serverAddress = request.RequestUri?.Host ?? string.Empty;");
        sb.AppendLine("            __activity?.SetTag(\"http.status_code\", __statusCode);");
        sb.AppendLine("            __activity?.SetTag(\"server.address\", __serverAddress);");
        sb.AppendLine("            var __elapsedMs = global::System.Diagnostics.Stopwatch.GetElapsedTime(__sw).TotalMilliseconds;");
        sb.AppendLine("            _requestsTotal.Add(1,");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"http.method\", __httpMethod),");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"http.status_code\", __statusCode),");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"server.address\", __serverAddress),");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"rest.method\", __RestMethodTag));");
        sb.AppendLine("            _requestDurationMs.Record(__elapsedMs,");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"http.method\", __httpMethod),");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"http.status_code\", __statusCode),");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"server.address\", __serverAddress),");
        sb.AppendLine("                new global::System.Collections.Generic.KeyValuePair<string, object?>(\"rest.method\", __RestMethodTag));");
        EmitResponseHandling(sb, method, ctArg, serializerExpr, indent: "            ");
        sb.AppendLine("        }");
        sb.AppendLine("#pragma warning disable EPC12");
        if (method.ReturnsResult)
            EmitResultCatches(sb, method, callerToken);
        sb.AppendLine("        catch (global::System.Exception __ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            __RecordFailure(__activity, __ex, __sw, __httpMethod, __RestMethodTag);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("#pragma warning restore EPC12");
    }

    // A Result-returning method returns a failure for a timeout or a transport error instead of
    // throwing. Cancellation the caller asked for still throws: it is not an error. Anything else,
    // such as a bug in a handler, reaches the rethrowing catch that follows these.
    private static void EmitResultCatches(StringBuilder sb, MethodModel method, string? callerToken)
    {
        var resultType = ResultTypeName(method);
        if (callerToken != null)
        {
            sb.AppendLine($"        catch (global::System.OperationCanceledException __ex) when ({callerToken}.IsCancellationRequested)");
            sb.AppendLine("        {");
            sb.AppendLine("            __RecordFailure(__activity, __ex, __sw, __httpMethod, __RestMethodTag);");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");
        }
        // Not requested by the caller, so it is HttpClient.Timeout or another timeout in the pipeline.
        sb.AppendLine("        catch (global::System.OperationCanceledException __ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            __RecordFailure(__activity, __ex, __sw, __httpMethod, __RestMethodTag);");
        sb.AppendLine($"            return {resultType}.Failure(");
        sb.AppendLine("                __CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Timeout, null, __ex));");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (global::System.Net.Http.HttpRequestException __ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            __RecordFailure(__activity, __ex, __sw, __httpMethod, __RestMethodTag);");
        sb.AppendLine($"            return {resultType}.Failure(");
        sb.AppendLine("                __CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Transport, null, __ex));");
        sb.AppendLine("        }");
    }

    private static void EmitResponseHandling(StringBuilder sb, MethodModel method, string ctArg, string serializerExpr, string indent = "        ")
    {
        var i1 = indent + "    ";
        var i2 = i1 + "    ";
        if (method.ReturnsVoid)
        {
            sb.AppendLine($"{indent}response.EnsureSuccessStatusCode();");
        }
        else if (method.ReturnsResult)
        {
            var resultType = ResultTypeName(method);
            sb.AppendLine($"{indent}if (response.IsSuccessStatusCode)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{i1}var responseStream = await response.Content.ReadAsStreamAsync({ctArg}).ConfigureAwait(false);");
            // Only the deserialize call is guarded: whatever the serializer throws, a JsonException or
            // a MemoryPack or MessagePack exception, means the body could not be read. Cancellation
            // is left to the method's cancellation catches.
            sb.AppendLine($"{i1}{method.InnerTypeName} content;");
            sb.AppendLine($"{i1}try");
            sb.AppendLine($"{i1}{{");
            sb.AppendLine($"{i2}content = (await {serializerExpr}.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false))!;");
            sb.AppendLine($"{i1}}}");
            sb.AppendLine($"{i1}catch (global::System.Exception __ex) when (__ex is not global::System.OperationCanceledException)");
            sb.AppendLine($"{i1}{{");
            sb.AppendLine($"{i2}__RecordFailure(__activity, __ex, __sw, __httpMethod, __RestMethodTag);");
            sb.AppendLine($"{i2}return {resultType}.Failure(");
            sb.AppendLine($"{i2}    __CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Deserialization, response, __ex));");
            sb.AppendLine($"{i1}}}");
            sb.AppendLine($"{i1}return {resultType}.Success(content);");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{i1}return {resultType}.Failure(");
            sb.AppendLine($"{i1}    __CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Status, response, null));");
            sb.AppendLine($"{indent}}}");
        }
        else
        {
            sb.AppendLine($"{indent}response.EnsureSuccessStatusCode();");
            sb.AppendLine($"{indent}var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);");
            sb.AppendLine($"{indent}return (await {serializerExpr}.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false))!;");
        }
    }

    private static string ResultTypeName(MethodModel method)
        => $"ZeroAlloc.Results.Result<{method.InnerTypeName}, ZeroAlloc.Rest.HttpError>";

    // Marks the span as failed and records the request duration. Every failure goes through here,
    // whether the method then rethrows or returns an HttpError, so failures still show in traces.
    private static void EmitRecordFailure(StringBuilder sb)
    {
        sb.AppendLine("    private static void __RecordFailure(global::System.Diagnostics.Activity? activity, global::System.Exception exception, long startTimestamp, string httpMethod, string restMethod)");
        sb.AppendLine("    {");
        sb.AppendLine("        activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, exception.Message);");
        sb.AppendLine("        var elapsedMs = global::System.Diagnostics.Stopwatch.GetElapsedTime(startTimestamp).TotalMilliseconds;");
        sb.AppendLine("        _requestDurationMs.Record(elapsedMs,");
        sb.AppendLine("            new global::System.Collections.Generic.KeyValuePair<string, object?>(\"http.method\", httpMethod),");
        sb.AppendLine("            new global::System.Collections.Generic.KeyValuePair<string, object?>(\"rest.method\", restMethod));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // The one place a generated client builds an HttpError. A response, when there is one, supplies
    // the status code and headers; the exception, when there is one, supplies the message. Keeping it
    // in one method leaves a single hook for reading the error body or mapping to a user error type.
    private static void EmitCreateHttpError(StringBuilder sb)
    {
        const string Headers = "global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Collections.Generic.IReadOnlyList<string>>";
        sb.AppendLine($"    private static readonly {Headers} __noHeaders =");
        sb.AppendLine("        new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, global::System.Collections.Generic.IReadOnlyList<string>>(");
        sb.AppendLine("            new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyList<string>>(0));");
        sb.AppendLine();
        sb.AppendLine("    private static global::ZeroAlloc.Rest.HttpError __CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind kind, global::System.Net.Http.HttpResponseMessage? response, global::System.Exception? exception)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.Net.HttpStatusCode statusCode;");
        sb.AppendLine($"        {Headers} headers;");
        sb.AppendLine("        if (response is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            statusCode = response.StatusCode;");
        // Header names are case-insensitive, and HttpClient reports known headers in its own
        // casing, such as X-Request-ID, so an ordinal lookup would miss them.
        sb.AppendLine("            var copy = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyList<string>>(global::System.StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("            foreach (var kvp in response.Headers)");
        sb.AppendLine("                copy[kvp.Key] = new global::System.Collections.Generic.List<string>(kvp.Value).AsReadOnly();");
        sb.AppendLine("            headers = copy;");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            // No response arrived. An HttpRequestException may still carry a status code.");
        sb.AppendLine("            statusCode = exception is global::System.Net.Http.HttpRequestException { StatusCode: { } requestStatus }");
        sb.AppendLine("                ? requestStatus");
        sb.AppendLine("                : (global::System.Net.HttpStatusCode)0;");
        sb.AppendLine("            headers = __noHeaders;");
        sb.AppendLine("        }");
        sb.AppendLine("        return new global::ZeroAlloc.Rest.HttpError(statusCode, headers, exception?.Message)");
        sb.AppendLine("        {");
        sb.AppendLine("            Kind = kind,");
        sb.AppendLine("            Exception = exception,");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string BuildParamList(IReadOnlyList<ParameterModel> parameters)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(parameters[i].TypeName).Append(' ').Append(parameters[i].Name);
        }
        return sb.ToString();
    }

    private static string Capitalize(string s)
    {
        if (s.Length == 0) return s;
        return char.ToUpper(s[0]) + s.Substring(1).ToLower();
    }

    /// <summary>
    /// Derives a collision-free private field name for an override serializer from its fully-qualified
    /// type name, deduplicating against already-assigned field names.
    /// "MyApp.OverrideSerializer" → "_overrideSerializer"; collisions get a numeric suffix (_overrideSerializer2, etc.)
    /// </summary>
    private static string StripGlobal(string typeName)
        => typeName.StartsWith("global::", System.StringComparison.Ordinal) ? typeName.Substring("global::".Length) : typeName;

    private static string GetSerializerFieldName(string fullTypeName, List<string> existingFieldNames)
    {
        fullTypeName = StripGlobal(fullTypeName);
        var simpleName = fullTypeName.Contains('.')
            ? fullTypeName.Substring(fullTypeName.LastIndexOf('.') + 1)
            : fullTypeName;
        if (simpleName.Length == 0) simpleName = "Serializer"; // defensive fallback
        var candidate = "_" + char.ToLower(simpleName[0]) + simpleName.Substring(1);
        if (!existingFieldNames.Contains(candidate)) return candidate;
        // Collision — append index
        var i = 2;
        while (existingFieldNames.Contains(candidate + i)) i++;
        return candidate + i;
    }

    private static ParameterModel? FindCancellationToken(IReadOnlyList<ParameterModel> parameters)
    {
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == ParameterKind.CancellationToken) return parameters[i];
        return null;
    }

    private static List<ParameterModel> FilterParameters(IReadOnlyList<ParameterModel> parameters, ParameterKind kind)
    {
        var result = new List<ParameterModel>();
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == kind) result.Add(parameters[i]);
        return result;
    }

    private static ParameterModel? FirstOrDefault(IReadOnlyList<ParameterModel> parameters, ParameterKind kind)
    {
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == kind) return parameters[i];
        return null;
    }
}
