using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using ZeroAlloc.Rest.Generator.Models;

namespace ZeroAlloc.Rest.Generator;

internal static class ClientEmitter
{
    internal static void Emit(SourceProductionContext ctx, ClientModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Rest;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public sealed partial class {model.ClassName} : {model.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly System.Net.Http.HttpClient _httpClient;");
        sb.AppendLine("    private readonly ZeroAlloc.Rest.IRestSerializer _serializer;");
        sb.AppendLine();
        sb.AppendLine($"    public {model.ClassName}(System.Net.Http.HttpClient httpClient, ZeroAlloc.Rest.IRestSerializer serializer)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("        _serializer = serializer;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in model.Methods)
            EmitMethod(sb, method);

        sb.AppendLine("}");

        ctx.AddSource($"{model.InterfaceName}.g.cs", sb.ToString());
    }

    private static void EmitMethod(StringBuilder sb, MethodModel method)
    {
        var ctParam = FindCancellationToken(method.Parameters);
        var ctArg = ctParam != null ? ctParam.Name : "default";
        var pathParams = FilterParameters(method.Parameters, ParameterKind.Path);
        var queryParams = FilterParameters(method.Parameters, ParameterKind.Query);
        var bodyParam = FirstOrDefault(method.Parameters, ParameterKind.Body);
        var headerParams = FilterParameters(method.Parameters, ParameterKind.Header);

        // For GET with no custom headers/body, use the dedicated HttpClient.GetAsync shortcut.
        // For all other methods (POST/PUT/PATCH/DELETE or GET with headers), use SendAsync.
        var useGetAsync = method.HttpMethod == "GET" && headerParams.Count == 0 && bodyParam == null;

        sb.AppendLine($"    public async {method.ReturnTypeName} {method.Name}({BuildParamList(method.Parameters)})");
        sb.AppendLine("    {");

        EmitUrlBuilding(sb, method.Route, pathParams, queryParams);

        if (useGetAsync)
        {
            EmitGetAsyncAndResponse(sb, method, ctArg);
        }
        else
        {
            EmitRequestCreation(sb, method, headerParams, bodyParam, ctArg);
            EmitSendAndResponse(sb, method, ctArg);
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitUrlBuilding(StringBuilder sb, string route,
        List<ParameterModel> pathParams, List<ParameterModel> queryParams)
    {
        if (pathParams.Count == 0 && queryParams.Count == 0)
        {
            sb.AppendLine($"        var url = \"{route}\";");
            return;
        }

        // Build the route with path interpolation
        var routeExpr = route;
        foreach (var p in pathParams)
            routeExpr = routeExpr.Replace("{" + p.Name + "}", $"{{Uri.EscapeDataString({p.Name}.ToString())}}");

        if (queryParams.Count == 0)
        {
            sb.AppendLine($"        var url = $\"{routeExpr}\";");
        }
        else
        {
            sb.AppendLine($"        var urlBase = $\"{routeExpr}\";");
            sb.AppendLine("        var urlBuilder = new System.Text.StringBuilder(urlBase).Append('?');");
            foreach (var q in queryParams)
                sb.AppendLine($"        urlBuilder.Append(\"{q.QueryName}=\").Append(Uri.EscapeDataString({q.Name}?.ToString() ?? string.Empty)).Append('&');");
            sb.AppendLine("        if (urlBuilder.Length > 0 && urlBuilder[urlBuilder.Length - 1] == '&') urlBuilder.Length--;");
            sb.AppendLine("        var url = urlBuilder.ToString();");
        }
    }

    private static void EmitRequestCreation(StringBuilder sb, MethodModel method,
        List<ParameterModel> headerParams, ParameterModel? bodyParam, string ctArg)
    {
        sb.AppendLine($"        using var request = new System.Net.Http.HttpRequestMessage(");
        sb.AppendLine($"            System.Net.Http.HttpMethod.{Capitalize(method.HttpMethod)},");
        sb.AppendLine($"            url);");

        foreach (var h in headerParams)
            sb.AppendLine($"        request.Headers.TryAddWithoutValidation(\"{h.HeaderName}\", {h.Name}?.ToString());");

        if (bodyParam != null)
        {
            sb.AppendLine("        var bodyStream = new System.IO.MemoryStream();");
            sb.AppendLine($"        await _serializer.SerializeAsync(bodyStream, {bodyParam.Name}, {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("        bodyStream.Position = 0;");
            sb.AppendLine("        request.Content = new System.Net.Http.StreamContent(bodyStream);");
            sb.AppendLine("        request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(_serializer.ContentType);");
        }
    }

    private static void EmitSendAndResponse(StringBuilder sb, MethodModel method, string ctArg)
    {
        sb.AppendLine($"        using var response = await _httpClient.SendAsync(request, {ctArg}).ConfigureAwait(false);");

        if (method.ReturnsVoid)
        {
            sb.AppendLine("        response.EnsureSuccessStatusCode();");
        }
        else if (method.ReturnsApiResponse)
        {
            sb.AppendLine($"        var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);");
            sb.AppendLine($"        var content = await _serializer.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("        var headers = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IReadOnlyList<string>>();");
            sb.AppendLine("        foreach (var header in response.Headers)");
            sb.AppendLine("            headers[header.Key] = new System.Collections.Generic.List<string>(header.Value).AsReadOnly();");
            sb.AppendLine($"        return new ZeroAlloc.Rest.ApiResponse<{method.InnerTypeName}>(content, response.StatusCode, headers);");
        }
        else
        {
            sb.AppendLine("        response.EnsureSuccessStatusCode();");
            sb.AppendLine($"        var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);");
            sb.AppendLine($"        return (await _serializer.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false))!;");
        }
    }

    private static void EmitGetAsyncAndResponse(StringBuilder sb, MethodModel method, string ctArg)
    {
        sb.AppendLine($"        using var response = await _httpClient.GetAsync(url, {ctArg}).ConfigureAwait(false);");

        if (method.ReturnsVoid)
        {
            sb.AppendLine("        response.EnsureSuccessStatusCode();");
        }
        else if (method.ReturnsApiResponse)
        {
            sb.AppendLine($"        var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);");
            sb.AppendLine($"        var content = await _serializer.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("        var headers = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IReadOnlyList<string>>();");
            sb.AppendLine("        foreach (var header in response.Headers)");
            sb.AppendLine("            headers[header.Key] = new System.Collections.Generic.List<string>(header.Value).AsReadOnly();");
            sb.AppendLine($"        return new ZeroAlloc.Rest.ApiResponse<{method.InnerTypeName}>(content, response.StatusCode, headers);");
        }
        else
        {
            sb.AppendLine("        response.EnsureSuccessStatusCode();");
            sb.AppendLine($"        var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);");
            sb.AppendLine($"        return (await _serializer.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false))!;");
        }
    }

    private static string BuildParamList(IReadOnlyList<ParameterModel> parameters)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(parameters[i].TypeName).Append(' ').Append(parameters[i].Name);
        }
        return sb.ToString();
    }

    private static string Capitalize(string s)
    {
        if (s.Length == 0) return s;
        return char.ToUpper(s[0]) + s.Substring(1).ToLower();
    }

    private static ParameterModel? FindCancellationToken(IReadOnlyList<ParameterModel> parameters)
    {
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == ParameterKind.CancellationToken) return parameters[i];
        return null;
    }

    private static List<ParameterModel> FilterParameters(IReadOnlyList<ParameterModel> parameters, ParameterKind kind)
    {
        var result = new List<ParameterModel>();
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == kind) result.Add(parameters[i]);
        return result;
    }

    private static ParameterModel? FirstOrDefault(IReadOnlyList<ParameterModel> parameters, ParameterKind kind)
    {
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == kind) return parameters[i];
        return null;
    }
}
