using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using ZeroAlloc.Rest.Generator.Models;

namespace ZeroAlloc.Rest.Generator;

internal static class ClientEmitter
{
    internal static void Emit(SourceProductionContext ctx, ClientModel model)
    {
        // Collect unique method-level serializer types (ordered, deduped)
        var overrideSerializers = new List<string>();
        foreach (var m in model.Methods)
        {
            if (m.SerializerTypeName != null && !overrideSerializers.Contains(m.SerializerTypeName))
                overrideSerializers.Add(m.SerializerTypeName);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Rest;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public sealed partial class {model.ClassName} : {model.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly System.Net.Http.HttpClient _httpClient;");
        sb.AppendLine("    private readonly ZeroAlloc.Rest.IRestSerializer _serializer;");
        foreach (var st in overrideSerializers)
            sb.AppendLine($"    private readonly {st} {GetSerializerFieldName(st)};");
        sb.AppendLine();

        // Build constructor parameter list
        var ctorParams = new System.Collections.Generic.List<string>
        {
            "System.Net.Http.HttpClient httpClient",
            "ZeroAlloc.Rest.IRestSerializer serializer"
        };
        foreach (var st in overrideSerializers)
        {
            var fieldName = GetSerializerFieldName(st);
            ctorParams.Add($"{st} {fieldName.Substring(1)}"); // strip leading '_' for param name
        }

        sb.AppendLine($"    public {model.ClassName}({string.Join(", ", ctorParams)})");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("        _serializer = serializer;");
        foreach (var st in overrideSerializers)
        {
            var fieldName = GetSerializerFieldName(st);
            sb.AppendLine($"        {fieldName} = {fieldName.Substring(1)};");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in model.Methods)
            EmitMethod(sb, method);

        sb.AppendLine("}");

        ctx.AddSource($"{model.InterfaceName}.g.cs", sb.ToString());
    }

    private static void EmitMethod(StringBuilder sb, MethodModel method)
    {
        var ctParam = FindCancellationToken(method.Parameters);
        var ctArg = ctParam != null ? ctParam.Name : "default";
        var pathParams = FilterParameters(method.Parameters, ParameterKind.Path);
        var queryParams = FilterParameters(method.Parameters, ParameterKind.Query);
        var bodyParam = FirstOrDefault(method.Parameters, ParameterKind.Body);
        var headerParams = FilterParameters(method.Parameters, ParameterKind.Header);

        // If the method has its own [Serializer], use that injected field; otherwise fall back to _serializer.
        var serializerExpr = method.SerializerTypeName != null
            ? GetSerializerFieldName(method.SerializerTypeName)
            : "_serializer";

        sb.AppendLine("    [System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"Serialization of arbitrary types may require dynamic code.\")]");
        sb.AppendLine("    [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"Serialization of arbitrary types may require unreferenced code.\")]");
        sb.AppendLine($"    public async {method.ReturnTypeName} {method.Name}({BuildParamList(method.Parameters)})");
        sb.AppendLine("    {");

        EmitUrlBuilding(sb, method.Route, pathParams, queryParams);
        EmitRequestCreation(sb, method, headerParams, bodyParam, ctArg, serializerExpr);
        EmitSendAndResponse(sb, method, ctArg, serializerExpr);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitUrlBuilding(StringBuilder sb, string route,
        List<ParameterModel> pathParams, List<ParameterModel> queryParams)
    {
        if (pathParams.Count == 0 && queryParams.Count == 0)
        {
            sb.AppendLine($"        var url = \"{route}\";");
            return;
        }

        // Build the route with path interpolation
        var routeExpr = route;
        foreach (var p in pathParams)
            routeExpr = routeExpr.Replace("{" + p.Name + "}", $"{{Uri.EscapeDataString({p.Name}.ToString())}}");

        if (queryParams.Count == 0)
        {
            sb.AppendLine($"        var url = $\"{routeExpr}\";");
        }
        else
        {
            sb.AppendLine($"        var urlBase = $\"{routeExpr}\";");
            sb.AppendLine("        var urlBuilder = new System.Text.StringBuilder(urlBase).Append('?');");
            foreach (var q in queryParams)
                if (q.IsNullable)
                    sb.AppendLine($"        if ({q.Name} != null) urlBuilder.Append(\"{q.QueryName}=\").Append(Uri.EscapeDataString({q.Name}!.ToString()!)).Append('&');");
                else
                    sb.AppendLine($"        urlBuilder.Append(\"{q.QueryName}=\").Append(Uri.EscapeDataString({q.Name}.ToString()!)).Append('&');");
            sb.AppendLine("        var lastChar = urlBuilder[urlBuilder.Length - 1];");
            sb.AppendLine("        if (lastChar == '&' || lastChar == '?') urlBuilder.Length--;");
            sb.AppendLine("        var url = urlBuilder.ToString();");
        }
    }

    private static void EmitRequestCreation(StringBuilder sb, MethodModel method,
        List<ParameterModel> headerParams, ParameterModel? bodyParam, string ctArg, string serializerExpr)
    {
        sb.AppendLine($"        using var request = new System.Net.Http.HttpRequestMessage(");
        sb.AppendLine($"            System.Net.Http.HttpMethod.{Capitalize(method.HttpMethod)},");
        sb.AppendLine($"            url);");
        sb.AppendLine($"        request.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue({serializerExpr}.ContentType));");

        foreach (var h in headerParams)
            sb.AppendLine($"        request.Headers.TryAddWithoutValidation(\"{h.HeaderName}\", {h.Name}?.ToString());");

        if (bodyParam != null)
        {
            sb.AppendLine("        var bodyStream = new System.IO.MemoryStream();");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            await {serializerExpr}.SerializeAsync(bodyStream, {bodyParam.Name}, {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch");
            sb.AppendLine("        {");
            sb.AppendLine("            bodyStream.Dispose();");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");
            sb.AppendLine("        bodyStream.Position = 0;");
            sb.AppendLine("        request.Content = new System.Net.Http.StreamContent(bodyStream);");
            sb.AppendLine($"        request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue({serializerExpr}.ContentType);");
        }
    }

    private static void EmitSendAndResponse(StringBuilder sb, MethodModel method, string ctArg, string serializerExpr)
    {
        sb.AppendLine($"        using var response = await _httpClient.SendAsync(request, {ctArg}).ConfigureAwait(false);");
        EmitResponseHandling(sb, method, ctArg, serializerExpr);
    }

    private static void EmitResponseHandling(StringBuilder sb, MethodModel method, string ctArg, string serializerExpr)
    {
        if (method.ReturnsVoid)
        {
            sb.AppendLine("        response.EnsureSuccessStatusCode();");
        }
        else if (method.ReturnsApiResponse)
        {
            sb.AppendLine($"        var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);");
            sb.AppendLine($"        var content = await {serializerExpr}.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("        var headers = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IReadOnlyList<string>>();");
            sb.AppendLine("        foreach (var header in response.Headers)");
            sb.AppendLine("            headers[header.Key] = new System.Collections.Generic.List<string>(header.Value).AsReadOnly();");
            sb.AppendLine($"        return new ZeroAlloc.Rest.ApiResponse<{method.InnerTypeName}>(content, response.StatusCode, headers);");
        }
        else
        {
            sb.AppendLine("        response.EnsureSuccessStatusCode();");
            sb.AppendLine($"        var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);");
            sb.AppendLine($"        return (await {serializerExpr}.DeserializeAsync<{method.InnerTypeName}>(responseStream, {ctArg}).ConfigureAwait(false))!;");
        }
    }

    private static string BuildParamList(IReadOnlyList<ParameterModel> parameters)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(parameters[i].TypeName).Append(' ').Append(parameters[i].Name);
        }
        return sb.ToString();
    }

    private static string Capitalize(string s)
    {
        if (s.Length == 0) return s;
        return char.ToUpper(s[0]) + s.Substring(1).ToLower();
    }

    /// <summary>
    /// Derives the private field name for an override serializer from its fully-qualified type name.
    /// "MyApp.OverrideSerializer" → "_overrideSerializer"
    /// </summary>
    private static string GetSerializerFieldName(string fullTypeName)
    {
        var simpleName = fullTypeName.Contains('.')
            ? fullTypeName.Substring(fullTypeName.LastIndexOf('.') + 1)
            : fullTypeName;
        return "_" + char.ToLower(simpleName[0]) + simpleName.Substring(1);
    }

    private static ParameterModel? FindCancellationToken(IReadOnlyList<ParameterModel> parameters)
    {
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == ParameterKind.CancellationToken) return parameters[i];
        return null;
    }

    private static List<ParameterModel> FilterParameters(IReadOnlyList<ParameterModel> parameters, ParameterKind kind)
    {
        var result = new List<ParameterModel>();
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == kind) result.Add(parameters[i]);
        return result;
    }

    private static ParameterModel? FirstOrDefault(IReadOnlyList<ParameterModel> parameters, ParameterKind kind)
    {
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].Kind == kind) return parameters[i];
        return null;
    }
}
