using System.Text;
using Microsoft.CodeAnalysis;
using ZeroAlloc.Rest.Generator.Models;

namespace ZeroAlloc.Rest.Generator;

internal static class DiEmitter
{
    internal static void Emit(SourceProductionContext ctx, ClientModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Rest;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("public static partial class GeneratedRestClientExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static Microsoft.Extensions.DependencyInjection.IHttpClientBuilder Add{model.InterfaceName}(");
        sb.AppendLine($"        this Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine($"        System.Action<ZeroAlloc.Rest.ZeroAllocClientOptions>? configure = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var options = new ZeroAlloc.Rest.ZeroAllocClientOptions();");
        sb.AppendLine("        configure?.Invoke(options);");
        sb.AppendLine("        if (options.SerializerType is not null)");
        sb.AppendLine("            services.AddSingleton(typeof(ZeroAlloc.Rest.IRestSerializer), options.SerializerType);");
        sb.AppendLine($"        services.AddTransient<{model.InterfaceName}, {model.ClassName}>();");
        sb.AppendLine($"        return services.AddHttpClient<{model.ClassName}>(client =>");
        sb.AppendLine("        {");
        sb.AppendLine("            if (options.BaseAddress is not null)");
        sb.AppendLine("                client.BaseAddress = options.BaseAddress;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.InterfaceName}.DI.g.cs", sb.ToString());
    }
}
