using System.Text;
using Microsoft.CodeAnalysis;
using ZeroAlloc.Rest.Generator.Models;

namespace ZeroAlloc.Rest.Generator;

internal static class DiEmitter
{
    internal static void Emit(SourceProductionContext ctx, ClientModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Rest;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{model.Accessibility} static partial class {model.ExtensionsClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IHttpClientBuilder Add{model.InterfaceName}(");
        sb.AppendLine($"        this IServiceCollection services,");
        sb.AppendLine($"        System.Action<ZeroAllocClientOptions>? configure = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var options = new ZeroAllocClientOptions();");
        sb.AppendLine("        configure?.Invoke(options);");
        sb.AppendLine($"        global::ZeroAlloc.Rest.GeneratedRestClient.AddSerializers<{model.ClassName}>(services, options);");

        // A named client plus a typed-client factory that calls the client's static Create, through
        // GeneratedRestClient because the client implements it explicitly, so the
        // serializer is resolved per client with no reflection or ActivatorUtilities.
        sb.AppendLine($"        return services.AddHttpClient(nameof({model.InterfaceName}), client =>");
        sb.AppendLine("        {");
        sb.AppendLine("            if (options.BaseAddress is not null)");
        sb.AppendLine("                client.BaseAddress = options.BaseAddress;");
        sb.AppendLine("        })");
        sb.AppendLine($"        .AddTypedClient<{model.InterfaceName}>(static (httpClient, sp) => global::ZeroAlloc.Rest.GeneratedRestClient.Create<{model.ClassName}>(httpClient, sp));");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{model.InterfaceName}.DI.g.cs", sb.ToString());
    }
}
