using System.Collections.Immutable;
using System.Reflection;
using System.Runtime.Loader;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Xunit;
using ZeroAlloc.Rest.Generator;

namespace ZeroAlloc.Rest.Tools.Tests;

// Compiles emitted code the way a consumer's build does: with the ZeroAlloc.Rest source generator,
// the System.Text.Json source generator and RouteTemplateAnalyzer, against real references.
// RouteTemplateAnalyzer skips generated code, so the <auto-generated/> marker is dropped and the file
// is compiled as ordinary source. A warning is a problem: consumers build with TreatWarningsAsErrors.
internal static class GeneratedCode
{
    private static readonly MetadataReference[] References =
    [
        .. Basic.Reference.Assemblies.Net100.References.All,
        MetadataReference.CreateFromFile(typeof(ZeroAlloc.Rest.HttpError).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(ZeroAlloc.Results.Result<,>).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(ZeroAlloc.Collections.HeapPooledList<>).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(ZeroAlloc.Rest.SystemTextJson.SystemTextJsonSerializer).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location),
        MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions).Assembly.Location),
    ];

    private static readonly CSharpParseOptions ParseOptions = new(LanguageVersion.Latest);

    private static readonly Lazy<ISourceGenerator> JsonSourceGenerator = new(LoadJsonSourceGenerator);

    // probe, when given, is compiled alongside: a public static class Probe with a public static
    // string Run(), which RunProbe calls.
    internal static Output Compile(string code, string? probe = null)
    {
        var trees = new List<SyntaxTree>
        {
            CSharpSyntaxTree.ParseText(code.Replace("// <auto-generated/>", "", StringComparison.Ordinal), ParseOptions, path: "Generated.cs"),
        };
        if (probe is not null)
            trees.Add(CSharpSyntaxTree.ParseText(probe, ParseOptions, path: "Probe.cs"));
        var compilation = CSharpCompilation.Create(
            "OpenApiClient",
            trees,
            References,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));

        CSharpGeneratorDriver
            .Create([new RestClientGenerator().AsSourceGenerator(), JsonSourceGenerator.Value], parseOptions: ParseOptions)
            .RunGeneratorsAndUpdateCompilation(compilation, out var output, out var generatorDiagnostics);

        var analyzerDiagnostics = output
            .WithAnalyzers([new RouteTemplateAnalyzer()])
            .GetAnalyzerDiagnosticsAsync().GetAwaiter().GetResult();

        // Every error counts, wherever it is. A warning counts when it has a source location: a
        // diagnostic about code, generated code included, always carries one. A location-less warning
        // describes this reference set instead. ZeroAlloc.Collections ships no net10.0 asset, so
        // binding its net9.0 one reports CS1701, which the SDK's default compile hides for consumers too.
        var problems = generatorDiagnostics
            .AddRange(analyzerDiagnostics)
            .AddRange(output.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error
                || (d.Severity == DiagnosticSeverity.Warning && d.Location.IsInSource)));
        return new Output(code, output, problems);
    }

    private static ISourceGenerator LoadJsonSourceGenerator()
    {
        var path = typeof(GeneratedCode).Assembly.GetCustomAttributes<AssemblyMetadataAttribute>()
            .Single(a => string.Equals(a.Key, "JsonSourceGenerator", StringComparison.Ordinal)).Value;
        Assert.True(File.Exists(path), $"The System.Text.Json source generator was not found at '{path}'.");
        var reference = new AnalyzerFileReference(path ?? "", new AnalyzerLoader());
        return Assert.Single(reference.GetGenerators(LanguageNames.CSharp));
    }

    internal sealed class Output(string code, Compilation compilation, ImmutableArray<Diagnostic> problems)
    {
        internal ImmutableArray<Diagnostic> Problems => problems;

        internal void AssertClean()
            => Assert.True(problems.IsEmpty, code + "\n" + string.Join("\n", problems));

        // Emits the assembly into a collectible load context and returns what Probe.Run returns.
        internal string RunProbe()
        {
            AssertClean();
            using var stream = new MemoryStream();
            var emitted = compilation.Emit(stream);
            Assert.True(emitted.Success, string.Join("\n", emitted.Diagnostics));
            stream.Position = 0;
            var context = new AssemblyLoadContext("probe", isCollectible: true);
            try
            {
                var run = context.LoadFromStream(stream).GetType("Probe")?.GetMethod("Run", BindingFlags.Public | BindingFlags.Static)
                    ?? throw new InvalidOperationException("The probe has no public static Probe.Run().");
                return run.Invoke(null, null) as string
                    ?? throw new InvalidOperationException("Probe.Run() returned no string.");
            }
            finally
            {
                context.Unload();
            }
        }
    }

    private sealed class AnalyzerLoader : IAnalyzerAssemblyLoader
    {
        public void AddDependencyLocation(string fullPath)
        {
        }

        public Assembly LoadFromPath(string fullPath) => AssemblyLoadContext.Default.LoadFromAssemblyPath(fullPath);
    }
}
