using Xunit;

namespace ZeroAlloc.Rest.Tools.Tests;

// Issue #338: the emitted interface must compile, and every route parameter must bind its route
// token, so that the source generator and RouteTemplateAnalyzer report nothing, ZRA005 included.
// Each test compiles the emitted interface with both, as a consumer's build does. RouteTemplateAnalyzer
// skips generated code, so the test drops the <auto-generated/> marker and compiles the interface as
// ordinary source; otherwise a mismatch would pass unseen, its value silently left out of the URL.
public class OpenApiRouteBindingTests
{
    private static string Spec(string paths) => $"""
        openapi: 3.0.0
        info:
          title: Test
          version: "1"
        paths:
        {paths}
        """;

    [Fact]
    public void PathParameter_WhoseNameDiffersInCaseFromCamelCase_BindsItsToken()
    {
        var code = Generate(Spec("""
              /users/{UserId}:
                get:
                  operationId: getUser
                  parameters:
                    - name: UserId
                      in: path
                      required: true
                      schema:
                        type: integer
                  responses:
                    '200':
                      description: OK
            """));

        Assert.Contains("[global::ZeroAlloc.Rest.Attributes.Get(\"/users/{userId}\")]", code);
        Assert.Contains("int userId", code);
        AssertCompilesClean(code);
    }

    [Fact]
    public void PathParameter_WithCharactersInvalidInCSharp_BindsItsToken()
    {
        var code = Generate(Spec("""
              /orgs/{org.id}/users/{user-id}:
                get:
                  operationId: getOrgUser
                  parameters:
                    - name: org.id
                      in: path
                      required: true
                      schema:
                        type: string
                    - name: user-id
                      in: path
                      required: true
                      schema:
                        type: integer
                  responses:
                    '200':
                      description: OK
            """));

        Assert.Contains("[global::ZeroAlloc.Rest.Attributes.Get(\"/orgs/{orgId}/users/{userId}\")]", code);
        Assert.Contains("string orgId, int userId", code);
        AssertCompilesClean(code);
    }

    [Fact]
    public void PathParameter_NamedAfterAKeyword_IsEscaped_AndBindsItsToken()
    {
        var code = Generate(Spec("""
              /types/{class}:
                get:
                  operationId: getType
                  parameters:
                    - name: class
                      in: path
                      required: true
                      schema:
                        type: string
                  responses:
                    '200':
                      description: OK
            """));

        Assert.Contains("[global::ZeroAlloc.Rest.Attributes.Get(\"/types/{class}\")]", code);
        Assert.Contains("string @class", code);
        AssertCompilesClean(code);
    }

    [Fact]
    public void PathParameter_DeclaredOnThePathItem_IsEmittedForEachOperation()
    {
        var code = Generate(Spec("""
              /users/{id}:
                parameters:
                  - name: id
                    in: path
                    required: true
                    schema:
                      type: integer
                get:
                  operationId: getUser
                  responses:
                    '200':
                      description: OK
                delete:
                  operationId: deleteUser
                  responses:
                    '204':
                      description: Deleted
            """));

        Assert.Contains("GetUserAsync(int id, global::System.Threading.CancellationToken ct = default)", code);
        Assert.Contains("DeleteUserAsync(int id, global::System.Threading.CancellationToken ct = default)", code);
        AssertCompilesClean(code);
    }

    [Fact]
    public void OperationParameter_OverridesThePathItemParameter_OfTheSameNameAndLocation()
    {
        var code = Generate(Spec("""
              /users/{id}:
                parameters:
                  - name: id
                    in: path
                    required: true
                    schema:
                      type: integer
                get:
                  operationId: getUser
                  parameters:
                    - name: id
                      in: path
                      required: true
                      schema:
                        type: string
                  responses:
                    '200':
                      description: OK
            """));

        Assert.Contains("GetUserAsync(string id, global::System.Threading.CancellationToken ct = default)", code);
        AssertCompilesClean(code);
    }

    [Fact]
    public void CookieParameter_IsSkipped_WithAWarning_InsteadOfBecomingARouteParameter()
    {
        var warnings = new List<OpenApiWarning>();
        var code = OpenApiInterfaceGenerator.Generate(Spec("""
              /users/{id}:
                get:
                  operationId: getUser
                  parameters:
                    - name: id
                      in: path
                      required: true
                      schema:
                        type: integer
                    - name: session
                      in: cookie
                      schema:
                        type: string
                  responses:
                    '200':
                      description: OK
            """), "MyApp", "IMyApi", warnings);

        Assert.Contains("GetUserAsync(int id, global::System.Threading.CancellationToken ct = default)", code);
        Assert.DoesNotContain("session)", code);
        Assert.Contains("// Cookie parameter 'session' is not emitted", code);
        var warning = Assert.Single(warnings);
        Assert.Equal("ZRT001", warning.Code);
        Assert.Contains("'session'", warning.Message);
        Assert.Contains("getUser", warning.Message);
        Assert.Contains("no cookie binding", warning.Message);
        AssertCompilesClean(code);
    }

    [Fact]
    public void QueryAndHeaderParameters_WithCharactersInvalidInCSharp_KeepTheirWireNames()
    {
        var code = Generate(Spec("""
              /users:
                get:
                  operationId: listUsers
                  parameters:
                    - name: page-size
                      in: query
                      schema:
                        type: integer
                    - name: PageToken
                      in: query
                      schema:
                        type: string
                    - name: X-Request-Id
                      in: header
                      schema:
                        type: string
                  responses:
                    '200':
                      description: OK
            """));

        Assert.Contains("[global::ZeroAlloc.Rest.Attributes.Query(Name = \"page-size\")] int? pageSize", code);
        Assert.Contains("[global::ZeroAlloc.Rest.Attributes.Query(Name = \"PageToken\")] string? pageToken", code);
        Assert.Contains("[global::ZeroAlloc.Rest.Attributes.Header(\"X-Request-Id\")] string? xRequestId", code);
        AssertCompilesClean(code);
    }

    [Fact]
    public void ParametersWhoseIdentifiersCollide_GetDistinctNames_AndThePathOneBindsItsToken()
    {
        var code = Generate(Spec("""
              /items/{id}:
                put:
                  operationId: putItem
                  parameters:
                    - name: id
                      in: query
                      schema:
                        type: string
                    - name: id
                      in: path
                      required: true
                      schema:
                        type: integer
                    - name: ct
                      in: query
                      schema:
                        type: string
                    - name: body
                      in: header
                      schema:
                        type: string
                  requestBody:
                    content:
                      application/json:
                        schema:
                          type: object
                  responses:
                    '204':
                      description: Updated
            """));

        Assert.Contains("[global::ZeroAlloc.Rest.Attributes.Put(\"/items/{id2}\")]", code);
        Assert.Contains(
            "PutItemAsync([global::ZeroAlloc.Rest.Attributes.Query] string? id, int id2, "
                + "[global::ZeroAlloc.Rest.Attributes.Query(Name = \"ct\")] string? ct2, "
                + "[global::ZeroAlloc.Rest.Attributes.Header(\"body\")] string? body2, "
                + "[global::ZeroAlloc.Rest.Attributes.Body] global::System.Collections.Generic.Dictionary<string, global::System.Text.Json.JsonElement>? body, "
                + "global::System.Threading.CancellationToken ct = default)",
            code);
        AssertCompilesClean(code);
    }

    [Fact]
    public void OperationId_WithCharactersInvalidInCSharp_ProducesAValidMethodName()
    {
        var code = Generate(Spec("""
              /users:
                get:
                  operationId: users.list
                  responses:
                    '200':
                      description: OK
              /health:
                get:
                  operationId: 2fa check
                  responses:
                    '200':
                      description: OK
            """));

        Assert.Contains("UsersListAsync(", code);
        Assert.Contains("_2faCheckAsync(", code);
        AssertCompilesClean(code);
    }

    private static string Generate(string spec)
    {
        var warnings = new List<OpenApiWarning>();
        var code = OpenApiInterfaceGenerator.Generate(spec, "MyApp", "IMyApi", warnings);
        Assert.Empty(warnings);
        return code;
    }

    private static void AssertCompilesClean(string code) => GeneratedCode.Compile(code).AssertClean();
}
