using System.Text;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Readers;

namespace ZeroAlloc.Rest.Tools;

internal static class OpenApiInterfaceGenerator
{
    internal static string Generate(string yamlOrJson, string @namespace, string interfaceName)
        => Generate(yamlOrJson, @namespace, interfaceName, new List<OpenApiWarning>());

    // Adds a message to warnings for each parameter of the spec the emitted interface leaves out,
    // so that the CLI and the MSBuild task can report it.
    internal static string Generate(string yamlOrJson, string @namespace, string interfaceName, List<OpenApiWarning> warnings)
    {
        var reader = new OpenApiStringReader();
        var document = reader.Read(yamlOrJson, out var diagnostic);

        if (document == null)
            throw new InvalidOperationException("Failed to parse OpenAPI document.");
        if (diagnostic.Errors.Count > 0)
        {
            var errors = string.Join("; ", diagnostic.Errors.Select(e => e.Message));
            throw new InvalidOperationException($"OpenAPI parse errors: {errors}");
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Rest.Attributes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine("[ZeroAllocRestClient]");
        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");

        if (document.Paths != null)
        {
            foreach (var (path, pathItem) in document.Paths)
                foreach (var (operationType, operation) in pathItem.Operations)
                    EmitMethod(sb, path, pathItem, operationType, operation, warnings);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    internal static string GenerateFromFile(string filePath, string @namespace, string interfaceName)
    {
        var content = File.ReadAllText(filePath);
        return Generate(content, @namespace, interfaceName);
    }

    internal static Task<string> GenerateFromFileAsync(
        string filePath, string @namespace, string interfaceName,
        CancellationToken ct = default)
        => GenerateFromFileAsync(filePath, @namespace, interfaceName, new List<OpenApiWarning>(), ct);

    internal static async Task<string> GenerateFromFileAsync(
        string filePath, string @namespace, string interfaceName, List<OpenApiWarning> warnings,
        CancellationToken ct)
    {
        var content = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName, warnings);
    }

    internal static Task<string> GenerateFromUrlAsync(
        string url, string @namespace, string interfaceName,
        CancellationToken ct = default)
        => GenerateFromUrlAsync(url, @namespace, interfaceName, new List<OpenApiWarning>(), ct);

    internal static async Task<string> GenerateFromUrlAsync(
        string url, string @namespace, string interfaceName, List<OpenApiWarning> warnings,
        CancellationToken ct)
    {
        using var http = new HttpClient();
        var content = await http.GetStringAsync(url, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName, warnings);
    }

    private static void EmitMethod(StringBuilder sb, string path, OpenApiPathItem pathItem,
        OperationType operationType, OpenApiOperation operation, List<OpenApiWarning> warnings)
    {
        var httpAttr = operationType switch
        {
            OperationType.Get    => "Get",
            OperationType.Post   => "Post",
            OperationType.Put    => "Put",
            OperationType.Patch  => "Patch",
            OperationType.Delete => "Delete",
            _ => null
        };
        if (httpAttr is null) return;

        var methodName = CSharpNames.ToIdentifier(CSharpNames.ToPascalCase(operation.OperationId
            ?? $"{httpAttr}{path.Replace("/", "_").Replace("{", "").Replace("}", "")}"), upperFirst: true) + "Async";
        var operationName = operation.OperationId ?? $"{httpAttr.ToUpperInvariant()} {path}";

        // The CancellationToken is always ct and the request body always body. A parameter whose
        // identifier would clash with either, or with an earlier parameter, gets a numeric suffix.
        var used = new HashSet<string>(StringComparer.Ordinal) { "ct" };
        if (operation.RequestBody != null)
            used.Add("body");

        var parameters = new List<string>();
        var comments = new List<string>();
        var routeIdentifiers = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var param in EffectiveParameters(pathItem, operation))
        {
            if (param.In is not (ParameterLocation.Path or ParameterLocation.Query or ParameterLocation.Header))
            {
                var (comment, warning) = Skipped(param, operationName);
                comments.Add(comment);
                warnings.Add(warning);
                continue;
            }

            var identifier = CSharpNames.Unique(CSharpNames.ToIdentifier(param.Name, upperFirst: false), used);
            // The source generator binds a {token} to the parameter of exactly its name, so the
            // route's token is rewritten to the identifier. See RewriteRoute.
            if (param.In == ParameterLocation.Path)
                routeIdentifiers[param.Name] = identifier;
            parameters.Add(Declaration(param, identifier));
        }

        if (operation.RequestBody != null)
            parameters.Add("[Body] object body");

        parameters.Add("CancellationToken ct = default");

        foreach (var comment in comments)
            sb.AppendLine($"    {comment}");
        sb.AppendLine($"    [{httpAttr}({CSharpNames.Literal(RewriteRoute(path, routeIdentifiers))})]");
        var returnType = GetReturnType(operation);
        sb.AppendLine($"    {returnType} {methodName}({string.Join(", ", parameters)});");
        sb.AppendLine();
    }

    private static string Declaration(OpenApiParameter param, string identifier)
    {
        var typeName = MapSchemaType(param.Schema);
        return param.In switch
        {
            ParameterLocation.Query when string.Equals(identifier, param.Name, StringComparison.Ordinal)
                => $"[Query] {typeName} {CSharpNames.Escape(identifier)}",
            ParameterLocation.Query => $"[Query(Name = {CSharpNames.Literal(param.Name)})] {typeName} {CSharpNames.Escape(identifier)}",
            ParameterLocation.Header => $"[Header({CSharpNames.Literal(param.Name)})] string {CSharpNames.Escape(identifier)}",
            _ => $"{typeName} {CSharpNames.Escape(identifier)}",
        };
    }

    // A parameter the interface cannot bind: a comment for the emitted method, and a warning.
    // Only a cookie parameter gets here; the OpenAPI reader rejects a parameter with no location.
    private static (string Comment, OpenApiWarning Warning) Skipped(OpenApiParameter param, string operationName)
    {
        // ZeroAlloc.Rest binds no cookies. Emitted without an attribute, a cookie parameter became
        // a route parameter with no token, and its value was never sent.
        return ($"// Cookie parameter '{param.Name}' is not emitted: ZeroAlloc.Rest has no cookie binding.",
            new OpenApiWarning(OpenApiWarning.CookieParameterNotEmitted,
                $"Operation '{operationName}': cookie parameter '{param.Name}' is not emitted, because "
                    + "ZeroAlloc.Rest has no cookie binding. Send the cookie from the HttpClient, for example "
                    + "with a CookieContainer on its handler."));
    }

    // The operation's parameters, after those its path item declares and the operation does not
    // override. OpenAPI identifies a parameter by its name and location.
    private static List<OpenApiParameter> EffectiveParameters(OpenApiPathItem pathItem, OpenApiOperation operation)
    {
        var operationParameters = operation.Parameters ?? new List<OpenApiParameter>();
        var result = new List<OpenApiParameter>();
        if (pathItem.Parameters != null)
        {
            foreach (var shared in pathItem.Parameters)
            {
                if (!operationParameters.Any(p => p.In == shared.In && string.Equals(p.Name, shared.Name, StringComparison.Ordinal)))
                    result.Add(shared);
            }
        }
        result.AddRange(operationParameters);
        return result;
    }

    // Replaces the {name} token of each path parameter with the identifier it was emitted under.
    private static string RewriteRoute(string path, Dictionary<string, string> routeIdentifiers)
    {
        var sb = new StringBuilder(path.Length);
        var i = 0;
        while (i < path.Length)
        {
            var open = path.IndexOf('{', i);
            var close = open < 0 ? -1 : path.IndexOf('}', open + 1);
            if (close < 0)
            {
                sb.Append(path, i, path.Length - i);
                break;
            }
            var name = path.Substring(open + 1, close - open - 1);
            sb.Append(path, i, open - i)
                .Append('{')
                .Append(routeIdentifiers.TryGetValue(name, out var identifier) ? identifier : name)
                .Append('}');
            i = close + 1;
        }
        return sb.ToString();
    }

    private static string GetReturnType(OpenApiOperation operation)
    {
        foreach (var (statusCode, response) in operation.Responses)
        {
            if (!statusCode.StartsWith("2", StringComparison.Ordinal)) continue;
            if (response.Content == null || response.Content.Count == 0) return "Task";
            foreach (var (_, content) in response.Content)
            {
                if (content.Schema == null) continue;
                return $"Task<{MapSchemaTypeForReturn(content.Schema)}>";
            }
        }
        return "Task";
    }

    private static string MapSchemaTypeForReturn(OpenApiSchema schema)
    {
        if (string.Equals(schema.Type, "array", StringComparison.Ordinal) && schema.Items != null)
            return $"List<{MapSchemaTypeForReturn(schema.Items)}>";
        if (schema.Reference != null)
            return CSharpNames.ToIdentifier(CSharpNames.ToPascalCase(schema.Reference.Id), upperFirst: true);
        return schema.Type switch
        {
            "integer" => "int",
            "number"  => "double",
            "boolean" => "bool",
            "string"  => "string",
            _         => "object"
        };
    }

    private static string MapSchemaType(OpenApiSchema? schema) => schema?.Type switch
    {
        "integer" => "int",
        "number"  => "double",
        "boolean" => "bool",
        _ => "string"
    };
}
