using System.Text;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Readers;
using Microsoft.OpenApi.Validations;
using Microsoft.OpenApi.Validations.Rules;

namespace ZeroAlloc.Rest.Tools;

internal static class OpenApiInterfaceGenerator
{
    internal static string Generate(string yamlOrJson, string @namespace, string interfaceName)
        => Generate(yamlOrJson, @namespace, interfaceName, new List<OpenApiDiagnostic>(), GenerationOptions.Default);

    internal static string Generate(string yamlOrJson, string @namespace, string interfaceName, List<OpenApiDiagnostic> warnings)
        => Generate(yamlOrJson, @namespace, interfaceName, warnings, GenerationOptions.Default);

    // Spec §3: one file per spec, in this order: the interface, the models it references, and the
    // JSON context covering both. Adds a warning for each part of the spec the file leaves out or
    // cannot type, so that the CLI and the MSBuild task can report it.
    internal static string Generate(string yamlOrJson, string @namespace, string interfaceName, List<OpenApiDiagnostic> warnings, GenerationOptions options)
    {
        var document = Parse(yamlOrJson);
        var baseName = WithoutInterfacePrefix(interfaceName);
        var contextName = baseName + "JsonContext";
        var builder = options.GenerateModels
            ? new SchemaModelBuilder(document, [interfaceName, baseName + "Client", contextName], warnings)
            : null;
        ISchemaTypeNamer namer = builder is null ? new ReferenceOnlyNamer(warnings) : builder;

        var methods = new StringBuilder();
        var serializable = new List<string>();
        if (document.Paths != null)
        {
            foreach (var (path, pathItem) in document.Paths)
            {
                foreach (var (operationType, operation) in pathItem.Operations)
                    OperationEmitter.Emit(methods, path, pathItem, operationType, operation, namer, serializable, warnings);
            }
        }
        var models = builder?.Build() ?? EquatableList<ModelDefinition>.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(@namespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("[global::ZeroAlloc.Rest.Attributes.ZeroAllocRestClient]");
        sb.Append("public interface ").AppendLine(interfaceName);
        sb.AppendLine("{");
        sb.Append(methods);
        sb.AppendLine("}");
        sb.AppendLine();
        ModelEmitter.Emit(sb, models);
        // A context with no [JsonSerializable] would leave JsonSerializerContext's abstract members
        // unimplemented, so a spec with no bodies gets none.
        var types = serializable.Concat(ModelEmitter.SerializableTypes(models)).ToList();
        if (types.Count > 0)
            JsonContextEmitter.Emit(sb, contextName, types, models);
        return sb.ToString();
    }

    internal static string GenerateFromFile(string filePath, string @namespace, string interfaceName)
    {
        var content = File.ReadAllText(filePath);
        return Generate(content, @namespace, interfaceName);
    }

    internal static Task<string> GenerateFromFileAsync(
        string filePath, string @namespace, string interfaceName,
        CancellationToken ct = default)
        => GenerateFromFileAsync(filePath, @namespace, interfaceName, new List<OpenApiDiagnostic>(), GenerationOptions.Default, ct);

    internal static async Task<string> GenerateFromFileAsync(
        string filePath, string @namespace, string interfaceName, List<OpenApiDiagnostic> warnings,
        GenerationOptions options, CancellationToken ct)
    {
        var content = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName, warnings, options);
    }

    internal static Task<string> GenerateFromUrlAsync(
        string url, string @namespace, string interfaceName,
        CancellationToken ct = default)
        => GenerateFromUrlAsync(url, @namespace, interfaceName, new List<OpenApiDiagnostic>(), GenerationOptions.Default, ct);

    internal static async Task<string> GenerateFromUrlAsync(
        string url, string @namespace, string interfaceName, List<OpenApiDiagnostic> warnings,
        GenerationOptions options, CancellationToken ct)
    {
        using var http = new HttpClient();
        var content = await http.GetStringAsync(url, ct).ConfigureAwait(false);
        return Generate(content, @namespace, interfaceName, warnings, options);
    }


    // Every reader error fails the run, except one rule: the reader's default rules require a
    // discriminator's property to be listed in required, which real specs often leave out. The
    // generated hierarchy reads and writes the discriminator whether or not it is required.
    private static OpenApiDocument Parse(string yamlOrJson)
    {
        var ruleSet = ValidationRuleSet.GetDefaultRuleSet();
        ruleSet.Remove(OpenApiSchemaRules.ValidateSchemaDiscriminator.Name);
        var reader = new OpenApiStringReader(new OpenApiReaderSettings { RuleSet = ruleSet });
        var document = reader.Read(yamlOrJson, out var diagnostic);
        if (document == null)
            throw new InvalidOperationException("Failed to parse OpenAPI document.");
        if (diagnostic.Errors.Count > 0)
        {
            var errors = string.Join("; ", diagnostic.Errors.Select(e => e.Message));
            throw new InvalidOperationException($"OpenAPI parse errors: {errors}");
        }
        return document;
    }

    // The Rest source generator's rule for the client name: IPetStoreClient gives PetStoreClientClient,
    // so the context is PetStoreClientJsonContext.
    private static string WithoutInterfacePrefix(string interfaceName)
        => interfaceName.Length > 1 && interfaceName[0] == 'I' ? interfaceName[1..] : interfaceName;
}
