// <auto-generated/>
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace ZeroAlloc.Rest.Generator.Tests;

public class GeneratorEmissionTests
{
    private static readonly System.Reflection.Assembly AttributesAssembly =
        typeof(ZeroAlloc.Rest.Attributes.ZeroAllocRestClientAttribute).Assembly;

    [Fact]
    public void GeneratedClass_HasConstructorWithHttpClientAndSerializer()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users")]
                System.Threading.Tasks.Task<string> ListAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IUserApi.g.cs");
        Assert.Contains("HttpClient", output);
        Assert.Contains("IRestSerializer", output);
    }

    [Fact]
    public void GeneratedClass_ImplementsInterface()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users")]
                System.Threading.Tasks.Task<string> ListAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IUserApi.g.cs");
        Assert.Contains("IUserApi", output);
        Assert.Contains("UserApiClient", output);
    }

    [Fact]
    public void GeneratedMethod_ContainsHttpGetCall()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Get("/orders/{id}")]
                System.Threading.Tasks.Task<string> GetOrderAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.Contains("SendAsync", output);
        Assert.Contains("/orders/", output);
    }

    [Fact]
    public void GeneratedMethod_Post_SerializesBody()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Post("/orders")]
                System.Threading.Tasks.Task<string> CreateAsync([Body] string body, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.Contains("SerializeAsync", output);
        Assert.Contains("StreamContent", output);
    }

    [Fact]
    public void GeneratedMethod_DeserializesResponse()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Get("/orders")]
                System.Threading.Tasks.Task<string> ListAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.Contains("DeserializeAsync", output);
    }

    [Fact]
    public void GeneratedMethod_Delete_NoDeserialization()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Delete("/orders/{id}")]
                System.Threading.Tasks.Task DeleteAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.DoesNotContain("DeserializeAsync", output);
        Assert.Contains("EnsureSuccessStatusCode", output);
    }

    [Fact]
    public void GeneratedMethod_UsesConfigureAwaitFalse()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IApi
            {
                [Get("/items")]
                System.Threading.Tasks.Task<string> GetAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IApi.g.cs");
        Assert.Contains("ConfigureAwait(false)", output);
    }

    [Fact]
    public void QueryParam_NonNullableValueType_NoNullGuard()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface ISearchApi
            {
                [Get("/items")]
                System.Threading.Tasks.Task<string> SearchAsync(
                    [Query] int page,
                    System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "ISearchApi.g.cs");
        Assert.DoesNotContain("if (page != null)", output);
        Assert.Contains("\"page=\"", output);
    }

    [Fact]
    public void QueryParam_NullableValueType_HasNullGuard()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface ISearchApi
            {
                [Get("/items")]
                System.Threading.Tasks.Task<string> SearchAsync(
                    [Query] int? page,
                    System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "ISearchApi.g.cs");
        Assert.Contains("if (page != null)", output);
    }

    [Fact]
    public void GeneratedMethod_SetsAcceptHeader()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users")]
                System.Threading.Tasks.Task<string> ListAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IUserApi.g.cs");
        Assert.Contains("request.Headers.Accept.Add", output);
        Assert.Contains("_serializer.ContentType", output);
    }

    [Fact]
    public void MethodLevelSerializer_UsesOverrideSerializerField()
    {
        var source = """
            using System.IO;
            using System.Threading;
            using System.Threading.Tasks;
            using ZeroAlloc.Rest;
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            public class OverrideSerializer : IRestSerializer
            {
                public string ContentType => "application/octet-stream";
                [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("")]
                [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("")]
                public ValueTask<T?> DeserializeAsync<T>(Stream stream, CancellationToken ct = default)
                    => ValueTask.FromResult<T?>(default);
                [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("")]
                [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("")]
                public ValueTask SerializeAsync<T>(Stream stream, T value, CancellationToken ct = default)
                    => ValueTask.CompletedTask;
            }
            [ZeroAllocRestClient]
            public interface IUploadApi
            {
                [Post("/upload")]
                [Serializer(typeof(OverrideSerializer))]
                Task UploadAsync([Body] string data, CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IUploadApi.g.cs");
        Assert.Contains("_overrideSerializer", output);
        Assert.Contains("ZeroAlloc.Rest.IRestSerializer overrideSerializer", output);
    }

    private const string SerializerStub = """
        public sealed class {0} : ZeroAlloc.Rest.IRestSerializer
        {{
            public string ContentType => "application/x-test";
            [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("")]
            [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("")]
            public System.Threading.Tasks.ValueTask<T?> DeserializeAsync<T>(System.IO.Stream stream, System.Threading.CancellationToken ct = default)
                => System.Threading.Tasks.ValueTask.FromResult<T?>(default);
            [System.Diagnostics.CodeAnalysis.RequiresDynamicCode("")]
            [System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("")]
            public System.Threading.Tasks.ValueTask SerializeAsync<T>(System.IO.Stream stream, T value, System.Threading.CancellationToken ct = default)
                => System.Threading.Tasks.ValueTask.CompletedTask;
        }}
        """;

    [Fact]
    public void GenericMethodSerializer_GetsAValidFieldName_AndCompiles()
    {
        var source = "#nullable enable\nusing ZeroAlloc.Rest.Attributes;\nnamespace MyApp;\n"
            + string.Format(System.Globalization.CultureInfo.InvariantCulture, SerializerStub, "Wrapper<TPayload>")
            + """

            public sealed class Payload { }
            [ZeroAllocRestClient]
            public interface IUploadApi
            {
                [Post("/upload")]
                [Serializer(typeof(Wrapper<Payload>))]
                System.Threading.Tasks.Task UploadAsync([Body] string data, System.Threading.CancellationToken ct = default);
            }
            """;

        var (output, errors) = CompileGenerated(source, "IUploadApi.g.cs");

        Assert.Empty(errors);
        Assert.Contains("private readonly ZeroAlloc.Rest.IRestSerializer _wrapper;", output);
    }

    [Fact]
    public void MethodSerializerNamedLikeAFixedField_GetsADistinctName_AndCompiles()
    {
        var source = "#nullable enable\nusing ZeroAlloc.Rest.Attributes;\nnamespace MyApp;\n"
            + string.Format(System.Globalization.CultureInfo.InvariantCulture, SerializerStub, "Serializer")
            + """

            [ZeroAllocRestClient]
            public interface IUploadApi
            {
                [Post("/upload")]
                [Serializer(typeof(Serializer))]
                System.Threading.Tasks.Task UploadAsync([Body] string data, System.Threading.CancellationToken ct = default);
            }
            """;

        var (output, errors) = CompileGenerated(source, "IUploadApi.g.cs");

        Assert.Empty(errors);
        Assert.Contains("private readonly ZeroAlloc.Rest.IRestSerializer _serializer2;", output);
    }

    [Fact]
    public void MethodSerializerNamedLikeAStaticField_GetsADistinctName_AndCompiles()
    {
        var source = "#nullable enable\nusing ZeroAlloc.Rest.Attributes;\nnamespace MyApp;\n"
            + string.Format(System.Globalization.CultureInfo.InvariantCulture, SerializerStub, "Meter")
            + """

            [ZeroAllocRestClient]
            public interface IUploadApi
            {
                [Post("/upload")]
                [Serializer(typeof(Meter))]
                System.Threading.Tasks.Task UploadAsync([Body] string data, System.Threading.CancellationToken ct = default);
            }
            """;

        var (output, errors) = CompileGenerated(source, "IUploadApi.g.cs");

        Assert.Empty(errors);
        Assert.Contains("private readonly ZeroAlloc.Rest.IRestSerializer _meter2;", output);
    }

    [Fact]
    public void MethodSerializerWhoseNameLowerCasesToAKeyword_GetsAnEscapedParameter_AndCompiles()
    {
        var source = "#nullable enable\nusing ZeroAlloc.Rest.Attributes;\nnamespace MyApp;\n"
            + string.Format(System.Globalization.CultureInfo.InvariantCulture, SerializerStub, "Class")
            + """

            [ZeroAllocRestClient]
            public interface IUploadApi
            {
                [Post("/upload")]
                [Serializer(typeof(Class))]
                System.Threading.Tasks.Task UploadAsync([Body] string data, System.Threading.CancellationToken ct = default);
            }
            """;

        var (output, errors) = CompileGenerated(source, "IUploadApi.g.cs");

        Assert.Empty(errors);
        Assert.Contains("ZeroAlloc.Rest.IRestSerializer @class)", output);
        Assert.Contains("_class = @class;", output);
    }

    private static (string Output, List<Diagnostic> Errors) CompileGenerated(string source, string hintName)
    {
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { CSharpSyntaxTree.ParseText(source) },
            Basic.Reference.Assemblies.Net100.References.All
                .Append(MetadataReference.CreateFromFile(AttributesAssembly.Location))
                .Append(MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location))
                .Append(MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions).Assembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var driver = CSharpGeneratorDriver
            .Create(new RestClientGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out var output, out _);

        var file = driver.GetRunResult().Results[0].GeneratedSources.First(f => f.HintName == hintName);
        var errors = output.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        return (file.SourceText.ToString(), errors);
    }

    private static readonly System.Reflection.Assembly ResultsAssembly =
        typeof(ZeroAlloc.Results.Result<,>).Assembly;

    [Fact]
    public void Generator_Result_ReturnType_EmitsResultWrapping()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users/{id}")]
                System.Threading.Tasks.Task<ZeroAlloc.Results.Result<string, ZeroAlloc.Rest.HttpError>> GetUserResultAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSourceWithResults(source, "IUserApi.g.cs");
        Assert.Contains("ZeroAlloc.Results.Result<", output);
        Assert.Contains("IsSuccessStatusCode", output);
        Assert.Contains(".Success(", output);
        Assert.Contains(".Failure(", output);
    }

    [Fact]
    public void Generator_Result_ReturnType_MapsTransportTimeoutAndDeserializationFailures()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users/{id}")]
                System.Threading.Tasks.Task<ZeroAlloc.Results.Result<string, ZeroAlloc.Rest.HttpError>> GetUserResultAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSourceWithResults(source, "IUserApi.g.cs");
        Assert.Contains("catch (global::System.OperationCanceledException __ex) when (ct.IsCancellationRequested)", output);
        Assert.Contains("HttpErrorKind.Timeout", output);
        Assert.Contains("catch (global::System.Net.Http.HttpRequestException __ex)", output);
        Assert.Contains("HttpErrorKind.Transport", output);
        Assert.Contains("HttpErrorKind.Deserialization", output);
        Assert.Contains("HttpErrorKind.Status", output);
        // One place builds every HttpError, so a later error mapper has a single hook.
        Assert.Equal(1, CountOccurrences(output, "new global::ZeroAlloc.Rest.HttpError("));
    }

    [Fact]
    public void Generator_Result_CreateHttpError_CopiesContentHeaders()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users/{id}")]
                System.Threading.Tasks.Task<ZeroAlloc.Results.Result<string, ZeroAlloc.Rest.HttpError>> GetUserResultAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSourceWithResults(source, "IUserApi.g.cs");
        Assert.Contains("foreach (var kvp in response.Headers)", output);
        Assert.Contains("foreach (var kvp in response.Content.Headers)", output);
    }

    private const string ResultApiSource = """
        using ZeroAlloc.Rest.Attributes;
        namespace MyApp;
        [ZeroAllocRestClient]
        public interface IUserApi
        {
            [Get("/users/{id}")]
            System.Threading.Tasks.Task<ZeroAlloc.Results.Result<string, ZeroAlloc.Rest.HttpError>> GetUserResultAsync(int id, System.Threading.CancellationToken ct = default);
        }
        """;

    [Fact]
    public void Generator_Result_ReadsTheErrorBodyOnlyOnTheStatusPath_WithTheDefaultCap()
    {
        var output = GetGeneratedSourceWithResults(ResultApiSource, "IUserApi.g.cs");

        Assert.Equal(1, CountOccurrences(output, "ReadErrorBodyAsync("));
        Assert.Contains(
            "var __errorBody = await global::ZeroAlloc.Rest.GeneratedRestClient.ReadErrorBodyAsync(response.Content, 65536, ct).ConfigureAwait(false);",
            output);
        Assert.Contains(
            "__CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Status, response, null, __errorBody.Body, __errorBody.Truncated));",
            output);
        // Transport, Timeout and Deserialization carry no body.
        Assert.Contains("__CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Timeout, null, __ex));", output);
        Assert.Contains("__CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Transport, null, __ex));", output);
        Assert.Contains("__CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Deserialization, response, __ex));", output);
    }

    [Fact]
    public void Generator_Result_SetsBodyContentTypeAndTruncatedOnTheError()
    {
        var output = GetGeneratedSourceWithResults(ResultApiSource, "IUserApi.g.cs");

        Assert.Contains("global::System.ReadOnlyMemory<byte> body = default, bool bodyTruncated = false)", output);
        Assert.Contains("contentType = response.Content.Headers.ContentType?.MediaType;", output);
        Assert.Contains("Body = body,", output);
        Assert.Contains("ContentType = contentType,", output);
        Assert.Contains("BodyTruncated = bodyTruncated,", output);
    }

    [Fact]
    public void Generator_Result_CustomCap_IsEmitted()
    {
        var source = ResultApiSource.Replace("[ZeroAllocRestClient]", "[ZeroAllocRestClient(MaxErrorBodyBytes = 1024)]");

        var output = GetGeneratedSourceWithResults(source, "IUserApi.g.cs");

        Assert.Contains("ReadErrorBodyAsync(response.Content, 1024, ct)", output);
    }

    [Fact]
    public void Generator_Result_ConstantExpressionCap_IsEmittedAsItsValue()
    {
        var source = ResultApiSource.Replace("[ZeroAllocRestClient]", "[ZeroAllocRestClient(MaxErrorBodyBytes = 4 * 1024)]");

        var output = GetGeneratedSourceWithResults(source, "IUserApi.g.cs");

        Assert.Contains("ReadErrorBodyAsync(response.Content, 4096,", output);
    }

    [Fact]
    public void Generator_Result_CallerCancellationCatch_PrecedesTheTimeoutCatch()
    {
        // The body read runs inside the method's try. Caller cancellation during that read must
        // reach the rethrowing catch, not the unfiltered one that turns cancellation into Timeout.
        const string OceCatch = "catch (global::System.OperationCanceledException __ex)";
        var output = GetGeneratedSourceWithResults(ResultApiSource, "IUserApi.g.cs");

        var callerCatch = output.IndexOf(OceCatch + " when (ct.IsCancellationRequested)", StringComparison.Ordinal);
        var timeoutCatch = -1;
        for (var i = output.IndexOf(OceCatch, StringComparison.Ordinal); i >= 0;
            i = output.IndexOf(OceCatch, i + 1, StringComparison.Ordinal))
        {
            var next = i + OceCatch.Length;
            if (next < output.Length && (output[next] == '\r' || output[next] == '\n'))
            {
                timeoutCatch = i;
                break;
            }
        }

        Assert.True(callerCatch >= 0, "The caller-cancellation catch is missing.");
        Assert.True(timeoutCatch >= 0, "The unfiltered Timeout catch is missing.");
        Assert.True(callerCatch < timeoutCatch, "The caller-cancellation catch must come before the Timeout catch.");
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-1)]
    public void Generator_Result_CapZeroOrLess_EmitsNoBodyRead(int cap)
    {
        var source = ResultApiSource.Replace(
            "[ZeroAllocRestClient]", $"[ZeroAllocRestClient(MaxErrorBodyBytes = {cap})]");

        var output = GetGeneratedSourceWithResults(source, "IUserApi.g.cs");

        Assert.DoesNotContain("ReadErrorBodyAsync", output);
        Assert.DoesNotContain("__errorBody", output);
        Assert.Contains("__CreateHttpError(global::ZeroAlloc.Rest.HttpErrorKind.Status, response, null));", output);
    }

    [Fact]
    public void Generator_Result_WithoutToken_PassesDefaultToTheBodyRead()
    {
        var source = ResultApiSource.Replace(", System.Threading.CancellationToken ct = default", "");

        var output = GetGeneratedSourceWithResults(source, "IUserApi.g.cs");

        Assert.Contains("ReadErrorBodyAsync(response.Content, 65536, default)", output);
    }

    [Fact]
    public void Generator_NonResult_ReturnType_KeepsRethrowingOnly()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users/{id}")]
                System.Threading.Tasks.Task<string> GetUserAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IUserApi.g.cs");
        Assert.DoesNotContain("HttpErrorKind", output);
        Assert.DoesNotContain("__CreateHttpError", output);
        Assert.DoesNotContain("ReadErrorBodyAsync", output);
        Assert.DoesNotContain("HttpRequestException", output);
        Assert.Contains("throw;", output);
    }

    [Fact]
    public void Generator_Result_ReturnType_CompilesForValueNullableAndTokenlessShapes()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            #nullable enable
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IShapesApi
            {
                [Get("/count")]
                System.Threading.Tasks.Task<ZeroAlloc.Results.Result<int, ZeroAlloc.Rest.HttpError>> CountAsync(System.Threading.CancellationToken ct = default);

                [Get("/maybe")]
                System.Threading.Tasks.Task<ZeroAlloc.Results.Result<string?, ZeroAlloc.Rest.HttpError>> MaybeAsync(System.Threading.CancellationToken ct = default);

                [Get("/no-token")]
                System.Threading.Tasks.Task<ZeroAlloc.Results.Result<string, ZeroAlloc.Rest.HttpError>> NoTokenAsync();

                [Get("/plain")]
                System.Threading.Tasks.Task<string> PlainAsync();
            }
            """;
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { CSharpSyntaxTree.ParseText(source) },
            Basic.Reference.Assemblies.Net100.References.All
                .Append(MetadataReference.CreateFromFile(AttributesAssembly.Location))
                .Append(MetadataReference.CreateFromFile(ResultsAssembly.Location))
                .Append(MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location))
                .Append(MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions).Assembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        CSharpGeneratorDriver
            .Create(new RestClientGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out var output, out _);

        var errors = output.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.True(errors.Count == 0, string.Join(Environment.NewLine, errors));
    }

    private static int CountOccurrences(string text, string value)
    {
        var count = 0;
        for (var i = text.IndexOf(value, StringComparison.Ordinal); i >= 0; i = text.IndexOf(value, i + value.Length, StringComparison.Ordinal))
            count++;
        return count;
    }

    [Fact]
    public void StaticHeader_OnMethod_EmittedInGeneratedCode()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IFileApi
            {
                [Get("/files/{id}")]
                [Header("Accept", Value = "application/octet-stream")]
                System.Threading.Tasks.Task<string> GetFileAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IFileApi.g.cs");
        Assert.Contains("\"Accept\"", output);
        Assert.Contains("\"application/octet-stream\"", output);
        Assert.Contains("TryAddWithoutValidation", output);
    }

    [Fact]
    public void QueryParam_Collection_EmitsForEachLoop()
    {
        var source = """
            using System.Collections.Generic;
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface ISearchApi
            {
                [Get("/items")]
                System.Threading.Tasks.Task<string> SearchAsync(
                    [Query] IEnumerable<string> tags,
                    System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "ISearchApi.g.cs");
        Assert.Contains("foreach", output);
        Assert.Contains("\"tags=\"", output);
        Assert.Contains("EscapeDataString", output);
    }

    [Fact]
    public void QueryParam_EmptyCollection_ProducesNoQueryString()
    {
        var source = """
            using System.Collections.Generic;
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface ISearchApi
            {
                [Get("/items")]
                System.Threading.Tasks.Task<string> SearchAsync(
                    [Query] IEnumerable<string>? tags,
                    System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "ISearchApi.g.cs");
        // The foreach branch must guard null items — no unconditional emission of empty values
        Assert.Contains("if (__item == null) continue;", output);
        Assert.DoesNotContain("__item?.ToString() ?? string.Empty", output);
    }

    [Fact]
    public void FormBody_EmitsFormUrlEncodedContent()
    {
        var source = """
            using System.Collections.Generic;
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface ITokenApi
            {
                [Post("/oauth/token")]
                System.Threading.Tasks.Task<string> GetTokenAsync(
                    [FormBody] Dictionary<string, string> form,
                    System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "ITokenApi.g.cs");
        Assert.Contains("FormUrlEncodedContent", output);
        Assert.DoesNotContain("SerializeAsync", output);
        Assert.DoesNotContain("StreamContent", output);
    }

    [Fact]
    public void ConflictingBodyAndFormBody_ReportsDiagnostic()
    {
        var source = """
            using System.Collections.Generic;
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface ITokenApi
            {
                [Post("/token")]
                System.Threading.Tasks.Task<string> BadAsync(
                    [Body] string body,
                    [FormBody] Dictionary<string, string> form,
                    System.Threading.CancellationToken ct = default);
            }
            """;
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { CSharpSyntaxTree.ParseText(source) },
            Basic.Reference.Assemblies.Net100.References.All
                .Append(MetadataReference.CreateFromFile(AttributesAssembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new RestClientGenerator();
        var driver = CSharpGeneratorDriver
            .Create(generator)
            .RunGenerators(compilation);

        var result = driver.GetRunResult();
        var diagnostic = Assert.Single(result.Results[0].Diagnostics, d => d.Id == "ZRA001");
        Assert.NotEqual(Location.None, diagnostic.Location);
        Assert.Equal("BadAsync", source.Substring(diagnostic.Location.SourceSpan.Start, diagnostic.Location.SourceSpan.Length));
        Assert.Equal(7, diagnostic.Location.GetLineSpan().StartLinePosition.Line);
        Assert.Equal(
            "Method 'BadAsync' has both [Body] and [FormBody] parameters; only one is allowed",
            diagnostic.GetMessage(System.Globalization.CultureInfo.InvariantCulture));
    }

    private static string GetGeneratedSource(string source, string hintName)
    {
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { CSharpSyntaxTree.ParseText(source) },
            Basic.Reference.Assemblies.Net100.References.All
                .Append(MetadataReference.CreateFromFile(AttributesAssembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new RestClientGenerator();
        var driver = CSharpGeneratorDriver
            .Create(generator)
            .RunGenerators(compilation);

        var result = driver.GetRunResult();
        var file = result.Results[0].GeneratedSources
            .FirstOrDefault(f => f.HintName == hintName);
        return file.SourceText?.ToString() ?? string.Empty;
    }

    private static string GetGeneratedSourceWithResults(string source, string hintName)
    {
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { CSharpSyntaxTree.ParseText(source) },
            Basic.Reference.Assemblies.Net100.References.All
                .Append(MetadataReference.CreateFromFile(AttributesAssembly.Location))
                .Append(MetadataReference.CreateFromFile(ResultsAssembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new RestClientGenerator();
        var driver = CSharpGeneratorDriver
            .Create(generator)
            .RunGenerators(compilation);

        var result = driver.GetRunResult();
        var file = result.Results[0].GeneratedSources
            .FirstOrDefault(f => f.HintName == hintName);
        return file.SourceText?.ToString() ?? string.Empty;
    }
}
