// <auto-generated/>
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace ZeroAlloc.Rest.Generator.Tests;

public class GeneratorEmissionTests
{
    private static readonly System.Reflection.Assembly AttributesAssembly =
        typeof(ZeroAlloc.Rest.Attributes.ZeroAllocRestClientAttribute).Assembly;

    [Fact]
    public void GeneratedClass_HasConstructorWithHttpClientAndSerializer()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users")]
                System.Threading.Tasks.Task<string> ListAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IUserApi.g.cs");
        Assert.Contains("HttpClient", output);
        Assert.Contains("IRestSerializer", output);
    }

    [Fact]
    public void GeneratedClass_ImplementsInterface()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users")]
                System.Threading.Tasks.Task<string> ListAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IUserApi.g.cs");
        Assert.Contains("IUserApi", output);
        Assert.Contains("UserApiClient", output);
    }

    [Fact]
    public void GeneratedMethod_ContainsHttpGetCall()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Get("/orders/{id}")]
                System.Threading.Tasks.Task<string> GetOrderAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.Contains("GetAsync", output);
        Assert.Contains("/orders/", output);
    }

    [Fact]
    public void GeneratedMethod_Post_SerializesBody()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Post("/orders")]
                System.Threading.Tasks.Task<string> CreateAsync([Body] string body, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.Contains("SerializeAsync", output);
        Assert.Contains("StreamContent", output);
    }

    [Fact]
    public void GeneratedMethod_DeserializesResponse()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Get("/orders")]
                System.Threading.Tasks.Task<string> ListAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.Contains("DeserializeAsync", output);
    }

    [Fact]
    public void GeneratedMethod_Delete_NoDeserialization()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IOrderApi
            {
                [Delete("/orders/{id}")]
                System.Threading.Tasks.Task DeleteAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IOrderApi.g.cs");
        Assert.DoesNotContain("DeserializeAsync", output);
        Assert.Contains("EnsureSuccessStatusCode", output);
    }

    [Fact]
    public void GeneratedMethod_UsesConfigureAwaitFalse()
    {
        var source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IApi
            {
                [Get("/items")]
                System.Threading.Tasks.Task<string> GetAsync(System.Threading.CancellationToken ct = default);
            }
            """;
        var output = GetGeneratedSource(source, "IApi.g.cs");
        Assert.Contains("ConfigureAwait(false)", output);
    }

    private static string GetGeneratedSource(string source, string hintName)
    {
        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { CSharpSyntaxTree.ParseText(source) },
            Basic.Reference.Assemblies.Net100.References.All
                .Append(MetadataReference.CreateFromFile(AttributesAssembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new RestClientGenerator();
        var driver = CSharpGeneratorDriver
            .Create(generator)
            .RunGenerators(compilation);

        var result = driver.GetRunResult();
        var file = result.Results[0].GeneratedSources
            .FirstOrDefault(f => f.HintName == hintName);
        return file.SourceText?.ToString() ?? string.Empty;
    }
}
