// <auto-generated/>
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using NetFabric.Hyperlinq.Analyzer;
using Xunit;

namespace ZeroAlloc.Rest.Generator.Tests;

// Every generated client whose methods return Result<T, HttpError> builds an HttpError inside
// __CreateHttpError. That method used to assign a Dictionary<,> to an IReadOnlyDictionary<,>
// local, which NetFabric.Hyperlinq.Analyzer flags as HLQ001 (assigning a collection with a
// value-type enumerator to an interface boxes the enumerator). The diagnostic landed in the
// generated file, so a consumer building with that analyzer and TreatWarningsAsErrors could not
// build, and could not scope a suppression to source-generator output. See
// https://github.com/ZeroAlloc-Net/ZeroAlloc.Rest/issues/335.
//
// This compiles the generated client with the real analyzer attached, the same way a consumer's
// build would, so a future regression is caught even if it takes a shape the text assertions in
// GeneratorEmissionTests do not anticipate.
public class GeneratorAnalyzerComplianceTests
{
    private static readonly System.Reflection.Assembly AttributesAssembly =
        typeof(ZeroAlloc.Rest.Attributes.ZeroAllocRestClientAttribute).Assembly;

    private static readonly System.Reflection.Assembly ResultsAssembly =
        typeof(ZeroAlloc.Results.Result<,>).Assembly;

    [Fact]
    public async Task GeneratedResultClient_Compiles_WithoutHyperlinqBoxingDiagnostics()
    {
        const string source = """
            using ZeroAlloc.Rest.Attributes;
            namespace MyApp;
            [ZeroAllocRestClient]
            public interface IUserApi
            {
                [Get("/users/{id}")]
                System.Threading.Tasks.Task<ZeroAlloc.Results.Result<string, ZeroAlloc.Rest.HttpError>> GetUserResultAsync(int id, System.Threading.CancellationToken ct = default);
            }
            """;

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            new[] { CSharpSyntaxTree.ParseText(source) },
            Basic.Reference.Assemblies.Net100.References.All
                .Append(MetadataReference.CreateFromFile(AttributesAssembly.Location))
                .Append(MetadataReference.CreateFromFile(ResultsAssembly.Location))
                .Append(MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location))
                .Append(MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions).Assembly.Location))
                .Append(MetadataReference.CreateFromFile(typeof(ZeroAlloc.Rest.DependencyInjection.DependencyInjectionMarker).Assembly.Location)),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        CSharpGeneratorDriver
            .Create(new RestClientGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _);

        var compileErrors = outputCompilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();
        Assert.Empty(compileErrors);

        var withAnalyzers = outputCompilation.WithAnalyzers(
            ImmutableArray.Create<DiagnosticAnalyzer>(new AssignmentBoxingAnalyzer()));
        var analyzerDiagnostics = await withAnalyzers.GetAnalyzerDiagnosticsAsync();

        Assert.Empty(analyzerDiagnostics.Where(d => d.Id == "HLQ001"));
    }
}
